-- V20260225_4: Spectacular alert templates for ALL operation types and events
-- Replaces V263 with improved templates using due_date_reference for dynamic dates
-- Covers initial events + post-emission events for all 10 product types
-- Both languages: ES and EN

DELETE FROM event_alert_template;

-- =============================================
-- LC_IMPORT — ADVISE (Initial) + Post-Emission — ES
-- =============================================
INSERT INTO event_alert_template (operation_type, event_code, alert_type, requirement_level, title_template, description_template, default_priority, assigned_role, due_days_offset, due_date_reference, tags, language, display_order) VALUES
('LC_IMPORT','ADVISE','DEADLINE','MANDATORY','Vencimiento de Carta de Crédito #{operationReference}','LC #{operationReference} por #{formattedAmount} #{currency} vence el #{expiryDate}. Verificar documentos y condiciones.','URGENT','ROLE_OPERATOR',-7,'EXPIRY_DATE','["vencimiento","critico","seguimiento"]','es',1),
('LC_IMPORT','ADVISE','DEADLINE','MANDATORY','Plazo presentación documentos UCP600 — #{operationReference}','Según UCP600 Art. 14, documentos deben presentarse dentro de 21 días desde embarque.','HIGH','ROLE_OPERATOR',21,'ISSUE_DATE','["documentacion","ucp600","plazo"]','es',2),
('LC_IMPORT','ADVISE','COMPLIANCE_CHECK','MANDATORY','Verificación KYC/AML — #{applicantName} / #{beneficiaryName}','Verificación compliance para partes de LC #{operationReference}. Validar contra listas de sanciones.','HIGH','ROLE_MANAGER',1,'EVENT_EXECUTION','["compliance","kyc","regulatorio"]','es',3),
('LC_IMPORT','ADVISE','CLIENT_CONTACT','MANDATORY','Notificación de emisión a #{applicantName}','Notificar a #{applicantName} que LC #{operationReference} fue avisada a #{beneficiaryName} vía #{advisingBankName}.','NORMAL','ROLE_OPERATOR',0,'EVENT_EXECUTION','["cliente","notificacion","emision"]','es',4),
('LC_IMPORT','ADVISE','FOLLOW_UP','RECOMMENDED','Seguimiento de embarque — #{operationReference}','Monitorear fecha límite de embarque para LC #{operationReference}. Coordinar con #{beneficiaryName}.','NORMAL','ROLE_OPERATOR',-30,'EXPIRY_DATE','["embarque","seguimiento","logistica"]','es',5),
('LC_IMPORT','ADVISE','TASK','RECOMMENDED','Provisión de fondos #{formattedAmount} — #{applicantName}','Verificar provisión de fondos para cubrir #{formattedAmount} #{currency} de LC #{operationReference}.','HIGH','ROLE_MANAGER',3,'EVENT_EXECUTION','["fondos","tesoreria","cobertura"]','es',6),
('LC_IMPORT','ADVISE','FOLLOW_UP','RECOMMENDED','Confirmación aviso #{advisingBankName}','Verificar que #{advisingBankName} confirmó recepción del aviso de LC #{operationReference}.','NORMAL','ROLE_OPERATOR',5,'EVENT_EXECUTION','["swift","bancos","aviso"]','es',7),
('LC_IMPORT','ADVISE','COMPLIANCE_CHECK','RECOMMENDED','Revisión exposición crediticia — #{applicantName}','Evaluar exposición crediticia total de #{applicantName} con LC #{operationReference}.','NORMAL','ROLE_MANAGER',7,'EVENT_EXECUTION','["riesgo","credito","exposicion"]','es',8),
('LC_IMPORT','ADVISE','REMINDER','RECOMMENDED','Verificar cobro comisiones — #{operationReference}','Confirmar cobro de comisiones de apertura de LC #{operationReference} a #{applicantName}.','NORMAL','ROLE_OPERATOR',2,'EVENT_EXECUTION','["comisiones","cobros","ingreso"]','es',9),
('LC_IMPORT','ADVISE','TASK','OPTIONAL','Completar expediente digital — #{operationReference}','Verificar digitalización completa de documentación de LC #{operationReference}.','LOW','ROLE_OPERATOR',5,'EVENT_EXECUTION','["documentacion","archivo","expediente"]','es',10),
('LC_IMPORT','ADVISE','FOLLOW_UP','OPTIONAL','Monitoreo riesgo país — #{beneficiaryName}','Revisar indicadores de riesgo país para jurisdicción de #{beneficiaryName}.','LOW','ROLE_MANAGER',10,'EVENT_EXECUTION','["riesgo","pais","monitoreo"]','es',11),
('LC_IMPORT','ADVISE','REMINDER','OPTIONAL','Revisión periódica de vigencia — #{operationReference}','Revisión periódica del estado de LC #{operationReference}.','LOW','ROLE_OPERATOR',-60,'EXPIRY_DATE','["revision","vigencia","periodico"]','es',12),
-- Post-emission events
('LC_IMPORT','AMEND','FOLLOW_UP','MANDATORY','Seguimiento solicitud de enmienda','Seguimiento a respuesta de enmienda de LC #{operationReference}. #{advisingBankName} debe responder.','HIGH','ROLE_OPERATOR',2,'EVENT_EXECUTION','["seguimiento","enmienda"]','es',1),
('LC_IMPORT','AMEND','REMINDER','RECOMMENDED','Verificar términos de enmienda','Revisar que nuevos términos de enmienda de LC #{operationReference} cumplan regulaciones.','NORMAL','ROLE_MANAGER',1,'EVENT_EXECUTION','["revision","enmienda"]','es',2),
('LC_IMPORT','CONFIRM','TASK','MANDATORY','Registrar confirmación bancaria','Registrar confirmación para LC #{operationReference} por #{formattedAmount} #{currency}.','HIGH','ROLE_OPERATOR',1,'EVENT_EXECUTION','["confirmacion"]','es',1),
('LC_IMPORT','PRESENT_DOCS','DEADLINE','MANDATORY','Plazo revisión documental (5 días)','Examinar documentos de LC #{operationReference} dentro de 5 días hábiles (UCP600 Art. 14).','URGENT','ROLE_OPERATOR',5,'EVENT_EXECUTION','["documentacion","ucp600","urgente"]','es',1),
('LC_IMPORT','PRESENT_DOCS','COMPLIANCE_CHECK','MANDATORY','Verificación compliance documental','Validar documentos de LC #{operationReference} contra regulaciones AML/KYC.','HIGH','ROLE_MANAGER',3,'EVENT_EXECUTION','["compliance","documentacion"]','es',2),
('LC_IMPORT','DISCREPANCY','FOLLOW_UP','MANDATORY','Seguimiento resolución discrepancias','Seguimiento a discrepancias en LC #{operationReference}. Verificar dispensa de #{applicantName}.','URGENT','ROLE_OPERATOR',2,'EVENT_EXECUTION','["discrepancia","urgente"]','es',1),
('LC_IMPORT','DISCREPANCY','CLIENT_CONTACT','MANDATORY','Notificar discrepancias al solicitante','Comunicar a #{applicantName} discrepancias en documentos de LC #{operationReference}.','HIGH','ROLE_OPERATOR',1,'EVENT_EXECUTION','["cliente","discrepancia"]','es',2),
('LC_IMPORT','ACCEPT_DOCS','TASK','MANDATORY','Preparar pago tras aceptación','Iniciar pago para LC #{operationReference}. Monto: #{formattedAmount} #{currency}.','HIGH','ROLE_OPERATOR',1,'EVENT_EXECUTION','["pago","documentacion"]','es',1),
('LC_IMPORT','PAYMENT','TASK','MANDATORY','Confirmar aplicación contable','Verificar registro contable del pago de LC #{operationReference} por #{formattedAmount} #{currency}.','HIGH','ROLE_MANAGER',1,'EVENT_EXECUTION','["pago","contabilidad"]','es',1),
('LC_IMPORT','PAYMENT','CLIENT_CONTACT','RECOMMENDED','Notificar pago al cliente','Comunicar a #{applicantName} el pago de LC #{operationReference}.','NORMAL','ROLE_OPERATOR',1,'EVENT_EXECUTION','["cliente","pago"]','es',2),
('LC_IMPORT','CLOSE','TASK','RECOMMENDED','Archivar expediente de LC','Archivar documentación completa de LC #{operationReference}.','LOW','ROLE_OPERATOR',5,'EVENT_EXECUTION','["archivo","cierre"]','es',1),
('LC_IMPORT','AMEND_ACCEPTED','TASK','MANDATORY','Actualizar términos de LC','Actualizar términos de LC #{operationReference} con enmienda aceptada.','HIGH','ROLE_OPERATOR',1,'EVENT_EXECUTION','["enmienda","actualizacion"]','es',1),
('LC_IMPORT','AMEND_REJECTED','CLIENT_CONTACT','MANDATORY','Notificar rechazo de enmienda','Informar a #{applicantName} rechazo de enmienda de LC #{operationReference}.','HIGH','ROLE_OPERATOR',1,'EVENT_EXECUTION','["cliente","enmienda","rechazo"]','es',1),
('LC_IMPORT','FREE_FORMAT_MESSAGE','FOLLOW_UP','RECOMMENDED','Seguimiento mensaje SWIFT libre','Seguimiento a respuesta del MT799/MT999 de LC #{operationReference}.','NORMAL','ROLE_OPERATOR',3,'EVENT_EXECUTION','["swift","seguimiento"]','es',1);

-- =============================================
-- LC_IMPORT — EN
-- =============================================
INSERT INTO event_alert_template (operation_type, event_code, alert_type, requirement_level, title_template, description_template, default_priority, assigned_role, due_days_offset, due_date_reference, tags, language, display_order) VALUES
('LC_IMPORT','ADVISE','DEADLINE','MANDATORY','Letter of Credit Expiry #{operationReference}','LC #{operationReference} for #{formattedAmount} #{currency} expires #{expiryDate}. Verify documents and conditions.','URGENT','ROLE_OPERATOR',-7,'EXPIRY_DATE','["expiry","critical","follow-up"]','en',1),
('LC_IMPORT','ADVISE','DEADLINE','MANDATORY','UCP600 Document Presentation Deadline — #{operationReference}','Per UCP600 Art. 14, documents must be presented within 21 days of shipment.','HIGH','ROLE_OPERATOR',21,'ISSUE_DATE','["documentation","ucp600","deadline"]','en',2),
('LC_IMPORT','ADVISE','COMPLIANCE_CHECK','MANDATORY','KYC/AML Verification — #{applicantName} / #{beneficiaryName}','Compliance check for LC #{operationReference} parties. Validate against sanctions lists.','HIGH','ROLE_MANAGER',1,'EVENT_EXECUTION','["compliance","kyc","regulatory"]','en',3),
('LC_IMPORT','ADVISE','CLIENT_CONTACT','MANDATORY','Issuance Notification to #{applicantName}','Notify #{applicantName} that LC #{operationReference} was advised to #{beneficiaryName} via #{advisingBankName}.','NORMAL','ROLE_OPERATOR',0,'EVENT_EXECUTION','["client","notification","issuance"]','en',4),
('LC_IMPORT','ADVISE','FOLLOW_UP','RECOMMENDED','Shipment Follow-up — #{operationReference}','Monitor shipment deadline for LC #{operationReference}. Coordinate with #{beneficiaryName}.','NORMAL','ROLE_OPERATOR',-30,'EXPIRY_DATE','["shipment","follow-up","logistics"]','en',5),
('LC_IMPORT','ADVISE','TASK','RECOMMENDED','Fund Provision #{formattedAmount} — #{applicantName}','Verify fund availability for #{formattedAmount} #{currency} of LC #{operationReference}.','HIGH','ROLE_MANAGER',3,'EVENT_EXECUTION','["funds","treasury","coverage"]','en',6),
('LC_IMPORT','ADVISE','FOLLOW_UP','RECOMMENDED','Advising Bank Acknowledgment #{advisingBankName}','Verify #{advisingBankName} confirmed receipt of LC #{operationReference} advice.','NORMAL','ROLE_OPERATOR',5,'EVENT_EXECUTION','["swift","banks","advice"]','en',7),
('LC_IMPORT','ADVISE','COMPLIANCE_CHECK','RECOMMENDED','Credit Exposure Review — #{applicantName}','Evaluate total credit exposure for #{applicantName} including LC #{operationReference}.','NORMAL','ROLE_MANAGER',7,'EVENT_EXECUTION','["risk","credit","exposure"]','en',8),
('LC_IMPORT','ADVISE','REMINDER','RECOMMENDED','Verify Commission Collection — #{operationReference}','Confirm opening commissions for LC #{operationReference} collected from #{applicantName}.','NORMAL','ROLE_OPERATOR',2,'EVENT_EXECUTION','["commissions","collections","revenue"]','en',9),
('LC_IMPORT','ADVISE','TASK','OPTIONAL','Complete Digital File — #{operationReference}','Verify complete digitization of LC #{operationReference} documentation.','LOW','ROLE_OPERATOR',5,'EVENT_EXECUTION','["documentation","archive","file"]','en',10),
('LC_IMPORT','ADVISE','FOLLOW_UP','OPTIONAL','Country Risk Monitoring — #{beneficiaryName}','Review country risk indicators for #{beneficiaryName} jurisdiction.','LOW','ROLE_MANAGER',10,'EVENT_EXECUTION','["risk","country","monitoring"]','en',11),
('LC_IMPORT','ADVISE','REMINDER','OPTIONAL','Periodic Validity Review — #{operationReference}','Periodic review of LC #{operationReference} status.','LOW','ROLE_OPERATOR',-60,'EXPIRY_DATE','["review","validity","periodic"]','en',12),
('LC_IMPORT','AMEND','FOLLOW_UP','MANDATORY','Amendment Request Follow-up','Follow up on amendment for LC #{operationReference}. #{advisingBankName} must respond.','HIGH','ROLE_OPERATOR',2,'EVENT_EXECUTION','["follow-up","amendment"]','en',1),
('LC_IMPORT','PRESENT_DOCS','DEADLINE','MANDATORY','Document Review Deadline (5 days)','Examine LC #{operationReference} documents within 5 banking days (UCP600 Art. 14).','URGENT','ROLE_OPERATOR',5,'EVENT_EXECUTION','["documentation","ucp600","urgent"]','en',1),
('LC_IMPORT','DISCREPANCY','FOLLOW_UP','MANDATORY','Discrepancy Resolution Follow-up','Follow up on discrepancies in LC #{operationReference}. Check #{applicantName} waiver.','URGENT','ROLE_OPERATOR',2,'EVENT_EXECUTION','["discrepancy","urgent"]','en',1),
('LC_IMPORT','ACCEPT_DOCS','TASK','MANDATORY','Prepare Payment After Acceptance','Initiate payment for LC #{operationReference}. Amount: #{formattedAmount} #{currency}.','HIGH','ROLE_OPERATOR',1,'EVENT_EXECUTION','["payment","documentation"]','en',1),
('LC_IMPORT','PAYMENT','TASK','MANDATORY','Confirm Accounting Entry','Verify accounting for LC #{operationReference} payment of #{formattedAmount} #{currency}.','HIGH','ROLE_MANAGER',1,'EVENT_EXECUTION','["payment","accounting"]','en',1),
('LC_IMPORT','CLOSE','TASK','RECOMMENDED','Archive LC File','Archive complete documentation for LC #{operationReference}.','LOW','ROLE_OPERATOR',5,'EVENT_EXECUTION','["archive","closure"]','en',1),
('LC_IMPORT','AMEND_ACCEPTED','TASK','MANDATORY','Update LC Terms','Update LC #{operationReference} terms with accepted amendment.','HIGH','ROLE_OPERATOR',1,'EVENT_EXECUTION','["amendment","update"]','en',1),
('LC_IMPORT','AMEND_REJECTED','CLIENT_CONTACT','MANDATORY','Notify Amendment Rejection','Inform #{applicantName} amendment for LC #{operationReference} was rejected.','HIGH','ROLE_OPERATOR',1,'EVENT_EXECUTION','["client","amendment","rejection"]','en',1);

-- =============================================
-- LC_EXPORT — ISSUE (Initial) + Post-Emission — ES
-- =============================================
INSERT INTO event_alert_template (operation_type, event_code, alert_type, requirement_level, title_template, description_template, default_priority, assigned_role, due_days_offset, due_date_reference, tags, language, display_order) VALUES
('LC_EXPORT','ISSUE','DEADLINE','MANDATORY','Vencimiento LC Exportación #{operationReference}','LC #{operationReference} por #{formattedAmount} #{currency} vence el #{expiryDate}. Monitorear estado.','URGENT','ROLE_OPERATOR',-7,'EXPIRY_DATE','["vencimiento","critico"]','es',1),
('LC_EXPORT','ISSUE','DEADLINE','MANDATORY','Plazo presentación documentos — #{operationReference}','Documentos deben presentarse dentro de 21 días desde embarque (UCP600 Art. 14).','HIGH','ROLE_OPERATOR',21,'ISSUE_DATE','["documentacion","ucp600","plazo"]','es',2),
('LC_EXPORT','ISSUE','COMPLIANCE_CHECK','MANDATORY','Verificación KYC/AML — #{applicantName} / #{beneficiaryName}','Verificación compliance para partes de LC #{operationReference}. Validar sanciones.','HIGH','ROLE_MANAGER',1,'EVENT_EXECUTION','["compliance","kyc","regulatorio"]','es',3),
('LC_EXPORT','ISSUE','TASK','MANDATORY','Verificar envío SWIFT MT700','Confirmar que MT700 de LC #{operationReference} fue enviado y entregado correctamente.','HIGH','ROLE_OPERATOR',1,'EVENT_EXECUTION','["swift","verificacion","emision"]','es',4),
('LC_EXPORT','ISSUE','FOLLOW_UP','RECOMMENDED','Seguimiento acuse MT730','Verificar recepción de acuse MT730 del banco avisador para LC #{operationReference}.','NORMAL','ROLE_OPERATOR',5,'EVENT_EXECUTION','["swift","bancos","aviso"]','es',5),
('LC_EXPORT','ISSUE','TASK','RECOMMENDED','Provisión de fondos #{formattedAmount}','Verificar disponibilidad de fondos para LC #{operationReference} por #{formattedAmount} #{currency}.','HIGH','ROLE_MANAGER',3,'EVENT_EXECUTION','["fondos","tesoreria"]','es',6),
('LC_EXPORT','ISSUE','COMPLIANCE_CHECK','RECOMMENDED','Revisión exposición crediticia','Evaluar exposición crediticia por LC #{operationReference} de #{formattedAmount} #{currency}.','NORMAL','ROLE_MANAGER',7,'EVENT_EXECUTION','["riesgo","credito","exposicion"]','es',7),
('LC_EXPORT','ISSUE','REMINDER','RECOMMENDED','Verificar cobro comisiones — #{operationReference}','Confirmar cobro de comisiones de emisión de LC #{operationReference}.','NORMAL','ROLE_OPERATOR',2,'EVENT_EXECUTION','["comisiones","cobros"]','es',8),
('LC_EXPORT','ISSUE','CLIENT_CONTACT','RECOMMENDED','Notificar emisión a #{applicantName}','Notificar a #{applicantName} la emisión de LC #{operationReference}.','NORMAL','ROLE_OPERATOR',0,'EVENT_EXECUTION','["cliente","notificacion"]','es',9),
('LC_EXPORT','ISSUE','TASK','OPTIONAL','Completar expediente digital','Digitalizar documentación de LC #{operationReference}.','LOW','ROLE_OPERATOR',5,'EVENT_EXECUTION','["documentacion","archivo"]','es',10),
('LC_EXPORT','ISSUE','FOLLOW_UP','OPTIONAL','Monitoreo riesgo país','Revisar riesgo país para jurisdicción de #{beneficiaryName}.','LOW','ROLE_MANAGER',10,'EVENT_EXECUTION','["riesgo","pais"]','es',11),
('LC_EXPORT','ISSUE','REMINDER','OPTIONAL','Revisión periódica vigencia','Revisión periódica de LC #{operationReference}.','LOW','ROLE_OPERATOR',-60,'EXPIRY_DATE','["revision","vigencia"]','es',12),
-- Post-emission
('LC_EXPORT','AMEND','FOLLOW_UP','MANDATORY','Seguimiento aceptación de enmienda','Verificar que beneficiario acepte enmienda MT707 de LC #{operationReference}.','HIGH','ROLE_OPERATOR',3,'EVENT_EXECUTION','["seguimiento","enmienda"]','es',1),
('LC_EXPORT','RECEIVE_DOCS','DEADLINE','MANDATORY','Iniciar examen documental','Examinar documentos recibidos para LC #{operationReference} dentro de 5 días hábiles (UCP600).','URGENT','ROLE_OPERATOR',5,'EVENT_EXECUTION','["documentacion","ucp600"]','es',1),
('LC_EXPORT','EXAMINE_DOCS','DEADLINE','MANDATORY','Completar examen documental','Finalizar examen de documentos de LC #{operationReference}. Determinar conformidad o discrepancias.','URGENT','ROLE_OPERATOR',3,'EVENT_EXECUTION','["documentacion","urgente"]','es',1),
('LC_EXPORT','EXAMINE_DOCS','COMPLIANCE_CHECK','MANDATORY','Verificación de sanciones','Verificar partes y documentos de LC #{operationReference} contra listas de sanciones.','HIGH','ROLE_MANAGER',2,'EVENT_EXECUTION','["compliance","sanciones"]','es',2),
('LC_EXPORT','DISCREPANCY','FOLLOW_UP','MANDATORY','Seguimiento resolución discrepancias','Seguimiento a respuesta del presentador sobre discrepancias en LC #{operationReference}.','HIGH','ROLE_OPERATOR',3,'EVENT_EXECUTION','["discrepancia","seguimiento"]','es',1),
('LC_EXPORT','ACCEPT_DOCS','TASK','MANDATORY','Procesar pago de LC','Iniciar pago a #{beneficiaryName} por LC #{operationReference}. Monto: #{formattedAmount} #{currency}.','HIGH','ROLE_OPERATOR',1,'EVENT_EXECUTION','["pago","documentacion"]','es',1),
('LC_EXPORT','PAYMENT','TASK','MANDATORY','Confirmar transferencia de fondos','Verificar transferencia de #{formattedAmount} #{currency} de LC #{operationReference} a #{beneficiaryName}.','HIGH','ROLE_MANAGER',1,'EVENT_EXECUTION','["pago","contabilidad"]','es',1),
('LC_EXPORT','PAYMENT','CLIENT_CONTACT','RECOMMENDED','Notificar pago efectuado','Comunicar a #{applicantName} el pago de LC #{operationReference}.','NORMAL','ROLE_OPERATOR',1,'EVENT_EXECUTION','["cliente","pago"]','es',2),
('LC_EXPORT','CLOSE','TASK','RECOMMENDED','Archivar expediente','Archivar documentación de LC #{operationReference}. Verificar saldos pendientes.','LOW','ROLE_OPERATOR',5,'EVENT_EXECUTION','["archivo","cierre"]','es',1);

-- =============================================
-- LC_EXPORT — EN
-- =============================================
INSERT INTO event_alert_template (operation_type, event_code, alert_type, requirement_level, title_template, description_template, default_priority, assigned_role, due_days_offset, due_date_reference, tags, language, display_order) VALUES
('LC_EXPORT','ISSUE','DEADLINE','MANDATORY','Export LC Expiry #{operationReference}','LC #{operationReference} for #{formattedAmount} #{currency} expires #{expiryDate}.','URGENT','ROLE_OPERATOR',-7,'EXPIRY_DATE','["expiry","critical"]','en',1),
('LC_EXPORT','ISSUE','DEADLINE','MANDATORY','Document Presentation Deadline — #{operationReference}','Documents must be presented within 21 days of shipment (UCP600 Art. 14).','HIGH','ROLE_OPERATOR',21,'ISSUE_DATE','["documentation","ucp600","deadline"]','en',2),
('LC_EXPORT','ISSUE','COMPLIANCE_CHECK','MANDATORY','KYC/AML Verification — #{applicantName} / #{beneficiaryName}','Compliance check for LC #{operationReference} parties. Validate sanctions.','HIGH','ROLE_MANAGER',1,'EVENT_EXECUTION','["compliance","kyc","regulatory"]','en',3),
('LC_EXPORT','ISSUE','TASK','MANDATORY','Verify SWIFT MT700 Delivery','Confirm MT700 for LC #{operationReference} was sent and delivered.','HIGH','ROLE_OPERATOR',1,'EVENT_EXECUTION','["swift","verification","issuance"]','en',4),
('LC_EXPORT','ISSUE','FOLLOW_UP','RECOMMENDED','MT730 Acknowledgment Follow-up','Verify receipt of MT730 from advising bank for LC #{operationReference}.','NORMAL','ROLE_OPERATOR',5,'EVENT_EXECUTION','["swift","banks","advice"]','en',5),
('LC_EXPORT','ISSUE','TASK','RECOMMENDED','Fund Provision #{formattedAmount}','Verify fund availability for LC #{operationReference} of #{formattedAmount} #{currency}.','HIGH','ROLE_MANAGER',3,'EVENT_EXECUTION','["funds","treasury"]','en',6),
('LC_EXPORT','ISSUE','COMPLIANCE_CHECK','RECOMMENDED','Credit Exposure Review','Evaluate credit exposure for LC #{operationReference} of #{formattedAmount} #{currency}.','NORMAL','ROLE_MANAGER',7,'EVENT_EXECUTION','["risk","credit","exposure"]','en',7),
('LC_EXPORT','ISSUE','REMINDER','RECOMMENDED','Verify Commission Collection — #{operationReference}','Confirm issuance commissions for LC #{operationReference} were collected.','NORMAL','ROLE_OPERATOR',2,'EVENT_EXECUTION','["commissions","collections"]','en',8),
('LC_EXPORT','ISSUE','CLIENT_CONTACT','RECOMMENDED','Notify Issuance to #{applicantName}','Notify #{applicantName} of LC #{operationReference} issuance.','NORMAL','ROLE_OPERATOR',0,'EVENT_EXECUTION','["client","notification"]','en',9),
('LC_EXPORT','ISSUE','TASK','OPTIONAL','Complete Digital File','Digitize LC #{operationReference} documentation.','LOW','ROLE_OPERATOR',5,'EVENT_EXECUTION','["documentation","archive"]','en',10),
('LC_EXPORT','ISSUE','FOLLOW_UP','OPTIONAL','Country Risk Monitoring','Review country risk for #{beneficiaryName} jurisdiction.','LOW','ROLE_MANAGER',10,'EVENT_EXECUTION','["risk","country"]','en',11),
('LC_EXPORT','ISSUE','REMINDER','OPTIONAL','Periodic Validity Review','Periodic review of LC #{operationReference}.','LOW','ROLE_OPERATOR',-60,'EXPIRY_DATE','["review","validity"]','en',12),
('LC_EXPORT','AMEND','FOLLOW_UP','MANDATORY','Amendment Acceptance Follow-up','Verify beneficiary accepts MT707 amendment for LC #{operationReference}.','HIGH','ROLE_OPERATOR',3,'EVENT_EXECUTION','["follow-up","amendment"]','en',1),
('LC_EXPORT','RECEIVE_DOCS','DEADLINE','MANDATORY','Start Document Examination','Examine documents for LC #{operationReference} within 5 banking days (UCP600).','URGENT','ROLE_OPERATOR',5,'EVENT_EXECUTION','["documentation","ucp600"]','en',1),
('LC_EXPORT','EXAMINE_DOCS','DEADLINE','MANDATORY','Complete Document Examination','Finalize document examination for LC #{operationReference}. Determine compliance or discrepancies.','URGENT','ROLE_OPERATOR',3,'EVENT_EXECUTION','["documentation","urgent"]','en',1),
('LC_EXPORT','EXAMINE_DOCS','COMPLIANCE_CHECK','MANDATORY','Sanctions Verification','Verify LC #{operationReference} parties and documents against sanctions lists.','HIGH','ROLE_MANAGER',2,'EVENT_EXECUTION','["compliance","sanctions"]','en',2),
('LC_EXPORT','DISCREPANCY','FOLLOW_UP','MANDATORY','Discrepancy Resolution Follow-up','Follow up on presenter response regarding discrepancies in LC #{operationReference}.','HIGH','ROLE_OPERATOR',3,'EVENT_EXECUTION','["discrepancy","follow-up"]','en',1),
('LC_EXPORT','ACCEPT_DOCS','TASK','MANDATORY','Process LC Payment','Initiate payment to #{beneficiaryName} for LC #{operationReference}. Amount: #{formattedAmount} #{currency}.','HIGH','ROLE_OPERATOR',1,'EVENT_EXECUTION','["payment","documentation"]','en',1),
('LC_EXPORT','PAYMENT','TASK','MANDATORY','Confirm Fund Transfer','Verify transfer of #{formattedAmount} #{currency} for LC #{operationReference} to #{beneficiaryName}.','HIGH','ROLE_MANAGER',1,'EVENT_EXECUTION','["payment","accounting"]','en',1),
('LC_EXPORT','PAYMENT','CLIENT_CONTACT','RECOMMENDED','Notify Payment Made','Communicate to #{applicantName} payment for LC #{operationReference}.','NORMAL','ROLE_OPERATOR',1,'EVENT_EXECUTION','["client","payment"]','en',2),
('LC_EXPORT','CLOSE','TASK','RECOMMENDED','Archive File','Archive LC #{operationReference} documentation. Verify pending balances.','LOW','ROLE_OPERATOR',5,'EVENT_EXECUTION','["archive","closure"]','en',1);

-- =============================================
-- GUARANTEE — ISSUE (Initial) + Post-Emission — ES
-- =============================================
INSERT INTO event_alert_template (operation_type, event_code, alert_type, requirement_level, title_template, description_template, default_priority, assigned_role, due_days_offset, due_date_reference, tags, language, display_order) VALUES
('GUARANTEE','ISSUE','DEADLINE','MANDATORY','Vencimiento de Garantía #{operationReference}','Garantía #{operationReference} por #{formattedAmount} #{currency} vence el #{expiryDate}. Monitorear estado y posible reclamo.','URGENT','ROLE_OPERATOR',-7,'EXPIRY_DATE','["vencimiento","critico","urdg758"]','es',1),
('GUARANTEE','ISSUE','DEADLINE','MANDATORY','Período de reclamo — #{operationReference}','Verificar claim period de garantía #{operationReference}. El beneficiario puede reclamar hasta el vencimiento.','HIGH','ROLE_OPERATOR',-15,'EXPIRY_DATE','["reclamo","plazo","urdg758"]','es',2),
('GUARANTEE','ISSUE','COMPLIANCE_CHECK','MANDATORY','Verificación KYC/AML — #{applicantName} / #{beneficiaryName}','Verificación compliance para garantía #{operationReference}. Validar contra sanciones.','HIGH','ROLE_MANAGER',1,'EVENT_EXECUTION','["compliance","kyc","regulatorio"]','es',3),
('GUARANTEE','ISSUE','CLIENT_CONTACT','MANDATORY','Notificación de emisión a #{applicantName}','Notificar a #{applicantName} la emisión de garantía #{operationReference} a favor de #{beneficiaryName}.','NORMAL','ROLE_OPERATOR',0,'EVENT_EXECUTION','["cliente","notificacion","emision"]','es',4),
('GUARANTEE','ISSUE','FOLLOW_UP','RECOMMENDED','Verificar contragarantía recibida','Verificar que se recibió contragarantía válida para garantía #{operationReference}.','NORMAL','ROLE_OPERATOR',5,'EVENT_EXECUTION','["contragarantia","verificacion"]','es',5),
('GUARANTEE','ISSUE','TASK','RECOMMENDED','Provisión de fondos #{formattedAmount}','Verificar provisión de fondos para garantía #{operationReference} por #{formattedAmount} #{currency}.','HIGH','ROLE_MANAGER',3,'EVENT_EXECUTION','["fondos","tesoreria"]','es',6),
('GUARANTEE','ISSUE','COMPLIANCE_CHECK','RECOMMENDED','Revisión exposición crediticia — #{applicantName}','Evaluar exposición total de #{applicantName} incluyendo garantía #{operationReference}.','NORMAL','ROLE_MANAGER',7,'EVENT_EXECUTION','["riesgo","credito","exposicion"]','es',7),
('GUARANTEE','ISSUE','REMINDER','RECOMMENDED','Verificar cobro comisiones — #{operationReference}','Confirmar cobro de comisiones de emisión de garantía #{operationReference}.','NORMAL','ROLE_OPERATOR',2,'EVENT_EXECUTION','["comisiones","cobros"]','es',8),
('GUARANTEE','ISSUE','FOLLOW_UP','RECOMMENDED','Seguimiento acuse MT760','Verificar recepción de acuse del beneficiario para garantía #{operationReference}.','NORMAL','ROLE_OPERATOR',5,'EVENT_EXECUTION','["swift","bancos"]','es',9),
('GUARANTEE','ISSUE','TASK','OPTIONAL','Completar expediente digital','Digitalizar documentación de garantía #{operationReference}.','LOW','ROLE_OPERATOR',5,'EVENT_EXECUTION','["documentacion","archivo"]','es',10),
('GUARANTEE','ISSUE','FOLLOW_UP','OPTIONAL','Monitoreo riesgo país','Revisar riesgo país para jurisdicción de #{beneficiaryName}.','LOW','ROLE_MANAGER',10,'EVENT_EXECUTION','["riesgo","pais"]','es',11),
('GUARANTEE','ISSUE','REMINDER','OPTIONAL','Revisión periódica vigencia — #{operationReference}','Revisión periódica de garantía #{operationReference}. Verificar condiciones.','LOW','ROLE_OPERATOR',-60,'EXPIRY_DATE','["revision","vigencia"]','es',12),
-- Post-emission
('GUARANTEE','AMEND','FOLLOW_UP','MANDATORY','Seguimiento enmienda de garantía','Verificar aceptación de enmienda de garantía #{operationReference} por beneficiario.','HIGH','ROLE_OPERATOR',3,'EVENT_EXECUTION','["seguimiento","enmienda"]','es',1),
('GUARANTEE','EXTEND','TASK','MANDATORY','Actualizar fecha de vencimiento','Actualizar vencimiento de garantía #{operationReference} y reprogramar alertas.','HIGH','ROLE_OPERATOR',1,'EVENT_EXECUTION','["vencimiento","actualizacion"]','es',1),
('GUARANTEE','EXTEND','CLIENT_CONTACT','RECOMMENDED','Notificar extensión al solicitante','Informar a #{applicantName} extensión de garantía #{operationReference}.','NORMAL','ROLE_OPERATOR',2,'EVENT_EXECUTION','["cliente","notificacion"]','es',2),
('GUARANTEE','CLAIM','TASK','MANDATORY','Evaluar validez del reclamo','Evaluar reclamo bajo garantía #{operationReference}. Monto: #{formattedAmount} #{currency}.','URGENT','ROLE_MANAGER',1,'EVENT_EXECUTION','["reclamo","urgente","evaluacion"]','es',1),
('GUARANTEE','CLAIM','CLIENT_CONTACT','MANDATORY','Notificar reclamo a #{applicantName}','URGENTE: Se recibió reclamo bajo garantía #{operationReference}. Notificar a #{applicantName}.','URGENT','ROLE_OPERATOR',0,'EVENT_EXECUTION','["cliente","reclamo","urgente"]','es',2),
('GUARANTEE','CLAIM','COMPLIANCE_CHECK','MANDATORY','Verificación fraude en reclamo','Verificar que reclamo bajo garantía #{operationReference} no presenta indicios de fraude.','HIGH','ROLE_MANAGER',1,'EVENT_EXECUTION','["compliance","fraude","reclamo"]','es',3),
('GUARANTEE','PAY_CLAIM','TASK','MANDATORY','Debitar cuenta del solicitante','Ejecutar débito a #{applicantName} por pago de reclamo de garantía #{operationReference}.','URGENT','ROLE_MANAGER',1,'EVENT_EXECUTION','["pago","contabilidad","reclamo"]','es',1),
('GUARANTEE','PAY_CLAIM','CLIENT_CONTACT','MANDATORY','Confirmar débito al solicitante','Notificar a #{applicantName} el débito por reclamo de garantía #{operationReference}.','HIGH','ROLE_OPERATOR',1,'EVENT_EXECUTION','["cliente","pago"]','es',2),
('GUARANTEE','RELEASE','TASK','RECOMMENDED','Archivar garantía liberada','Archivar documentación de garantía #{operationReference} liberada.','LOW','ROLE_OPERATOR',5,'EVENT_EXECUTION','["archivo","cierre"]','es',1),
('GUARANTEE','EXPIRE','TASK','RECOMMENDED','Liberar provisión de fondos','Liberar provisión asociada a garantía #{operationReference} tras vencimiento.','NORMAL','ROLE_MANAGER',3,'EVENT_EXECUTION','["contabilidad","cierre"]','es',1),
('GUARANTEE','EXPIRE','CLIENT_CONTACT','OPTIONAL','Notificar vencimiento al solicitante','Informar a #{applicantName} que garantía #{operationReference} expiró sin reclamo.','LOW','ROLE_OPERATOR',2,'EVENT_EXECUTION','["cliente","notificacion"]','es',2);

-- =============================================
-- GUARANTEE — EN
-- =============================================
INSERT INTO event_alert_template (operation_type, event_code, alert_type, requirement_level, title_template, description_template, default_priority, assigned_role, due_days_offset, due_date_reference, tags, language, display_order) VALUES
('GUARANTEE','ISSUE','DEADLINE','MANDATORY','Guarantee Expiry #{operationReference}','Guarantee #{operationReference} for #{formattedAmount} #{currency} expires #{expiryDate}. Monitor status and potential claim.','URGENT','ROLE_OPERATOR',-7,'EXPIRY_DATE','["expiry","critical","urdg758"]','en',1),
('GUARANTEE','ISSUE','DEADLINE','MANDATORY','Claim Period — #{operationReference}','Verify claim period for guarantee #{operationReference}. Beneficiary may claim until expiry.','HIGH','ROLE_OPERATOR',-15,'EXPIRY_DATE','["claim","deadline","urdg758"]','en',2),
('GUARANTEE','ISSUE','COMPLIANCE_CHECK','MANDATORY','KYC/AML Verification — #{applicantName} / #{beneficiaryName}','Compliance check for guarantee #{operationReference}. Validate sanctions.','HIGH','ROLE_MANAGER',1,'EVENT_EXECUTION','["compliance","kyc","regulatory"]','en',3),
('GUARANTEE','ISSUE','CLIENT_CONTACT','MANDATORY','Issuance Notification to #{applicantName}','Notify #{applicantName} of guarantee #{operationReference} issuance in favor of #{beneficiaryName}.','NORMAL','ROLE_OPERATOR',0,'EVENT_EXECUTION','["client","notification","issuance"]','en',4),
('GUARANTEE','ISSUE','FOLLOW_UP','RECOMMENDED','Verify Counter-Guarantee Received','Verify valid counter-guarantee received for guarantee #{operationReference}.','NORMAL','ROLE_OPERATOR',5,'EVENT_EXECUTION','["counter-guarantee","verification"]','en',5),
('GUARANTEE','ISSUE','TASK','RECOMMENDED','Fund Provision #{formattedAmount}','Verify fund provision for guarantee #{operationReference} of #{formattedAmount} #{currency}.','HIGH','ROLE_MANAGER',3,'EVENT_EXECUTION','["funds","treasury"]','en',6),
('GUARANTEE','ISSUE','COMPLIANCE_CHECK','RECOMMENDED','Credit Exposure Review — #{applicantName}','Evaluate total exposure for #{applicantName} including guarantee #{operationReference}.','NORMAL','ROLE_MANAGER',7,'EVENT_EXECUTION','["risk","credit","exposure"]','en',7),
('GUARANTEE','ISSUE','REMINDER','RECOMMENDED','Verify Commission Collection — #{operationReference}','Confirm issuance commissions for guarantee #{operationReference} collected.','NORMAL','ROLE_OPERATOR',2,'EVENT_EXECUTION','["commissions","collections"]','en',8),
('GUARANTEE','ISSUE','FOLLOW_UP','RECOMMENDED','MT760 Acknowledgment Follow-up','Verify beneficiary acknowledgment for guarantee #{operationReference}.','NORMAL','ROLE_OPERATOR',5,'EVENT_EXECUTION','["swift","banks"]','en',9),
('GUARANTEE','ISSUE','TASK','OPTIONAL','Complete Digital File','Digitize guarantee #{operationReference} documentation.','LOW','ROLE_OPERATOR',5,'EVENT_EXECUTION','["documentation","archive"]','en',10),
('GUARANTEE','ISSUE','FOLLOW_UP','OPTIONAL','Country Risk Monitoring','Review country risk for #{beneficiaryName} jurisdiction.','LOW','ROLE_MANAGER',10,'EVENT_EXECUTION','["risk","country"]','en',11),
('GUARANTEE','ISSUE','REMINDER','OPTIONAL','Periodic Validity Review — #{operationReference}','Periodic review of guarantee #{operationReference}.','LOW','ROLE_OPERATOR',-60,'EXPIRY_DATE','["review","validity"]','en',12),
('GUARANTEE','AMEND','FOLLOW_UP','MANDATORY','Guarantee Amendment Follow-up','Verify beneficiary acceptance of guarantee #{operationReference} amendment.','HIGH','ROLE_OPERATOR',3,'EVENT_EXECUTION','["follow-up","amendment"]','en',1),
('GUARANTEE','EXTEND','TASK','MANDATORY','Update Expiry Date','Update guarantee #{operationReference} expiry and reschedule alerts.','HIGH','ROLE_OPERATOR',1,'EVENT_EXECUTION','["expiry","update"]','en',1),
('GUARANTEE','CLAIM','TASK','MANDATORY','Evaluate Claim Validity','Evaluate claim under guarantee #{operationReference}. Amount: #{formattedAmount} #{currency}.','URGENT','ROLE_MANAGER',1,'EVENT_EXECUTION','["claim","urgent","evaluation"]','en',1),
('GUARANTEE','CLAIM','CLIENT_CONTACT','MANDATORY','Notify Claim to #{applicantName}','URGENT: Claim received under guarantee #{operationReference}. Notify #{applicantName}.','URGENT','ROLE_OPERATOR',0,'EVENT_EXECUTION','["client","claim","urgent"]','en',2),
('GUARANTEE','PAY_CLAIM','TASK','MANDATORY','Debit Applicant Account','Execute debit to #{applicantName} for guarantee #{operationReference} claim payment.','URGENT','ROLE_MANAGER',1,'EVENT_EXECUTION','["payment","accounting","claim"]','en',1),
('GUARANTEE','RELEASE','TASK','RECOMMENDED','Archive Released Guarantee','Archive guarantee #{operationReference} documentation after release.','LOW','ROLE_OPERATOR',5,'EVENT_EXECUTION','["archive","closure"]','en',1),
('GUARANTEE','EXPIRE','TASK','RECOMMENDED','Release Fund Provision','Release fund provision for guarantee #{operationReference} after expiry.','NORMAL','ROLE_MANAGER',3,'EVENT_EXECUTION','["accounting","closure"]','en',1);

-- =============================================
-- COLLECTION — SEND_COLLECTION (Initial) + Post-Emission — ES
-- =============================================
INSERT INTO event_alert_template (operation_type, event_code, alert_type, requirement_level, title_template, description_template, default_priority, assigned_role, due_days_offset, due_date_reference, tags, language, display_order) VALUES
('COLLECTION','SEND_COLLECTION','DEADLINE','MANDATORY','Vencimiento de Cobranza #{operationReference}','Cobranza #{operationReference} por #{formattedAmount} #{currency} vence el #{expiryDate}. Verificar estado de pago/aceptación.','URGENT','ROLE_OPERATOR',-7,'EXPIRY_DATE','["vencimiento","critico","urc522"]','es',1),
('COLLECTION','SEND_COLLECTION','FOLLOW_UP','MANDATORY','Seguimiento aceptación del girado','Dar seguimiento a respuesta de aceptación/pago del girado para cobranza #{operationReference}.','HIGH','ROLE_OPERATOR',7,'EVENT_EXECUTION','["seguimiento","girado","aceptacion"]','es',2),
('COLLECTION','SEND_COLLECTION','COMPLIANCE_CHECK','MANDATORY','Verificación KYC/AML — partes','Verificación compliance para cobranza #{operationReference}. Validar contra sanciones.','HIGH','ROLE_MANAGER',1,'EVENT_EXECUTION','["compliance","kyc","regulatorio"]','es',3),
('COLLECTION','SEND_COLLECTION','CLIENT_CONTACT','MANDATORY','Notificación envío a #{applicantName}','Notificar a #{applicantName} que cobranza #{operationReference} fue enviada al banco cobrador.','NORMAL','ROLE_OPERATOR',0,'EVENT_EXECUTION','["cliente","notificacion"]','es',4),
('COLLECTION','SEND_COLLECTION','FOLLOW_UP','RECOMMENDED','Seguimiento acuse banco cobrador','Verificar recepción de acuse MT410 del banco cobrador para cobranza #{operationReference}.','NORMAL','ROLE_OPERATOR',5,'EVENT_EXECUTION','["swift","bancos","aviso"]','es',5),
('COLLECTION','SEND_COLLECTION','TASK','RECOMMENDED','Verificar envío documentos físicos','Confirmar envío de documentos físicos de cobranza #{operationReference} por courier.','NORMAL','ROLE_OPERATOR',1,'EVENT_EXECUTION','["documentacion","envio"]','es',6),
('COLLECTION','SEND_COLLECTION','DEADLINE','RECOMMENDED','Plazo protesto si impago','Si el girado no paga/acepta cobranza #{operationReference}, iniciar protesto según instrucciones.','HIGH','ROLE_OPERATOR',-14,'EXPIRY_DATE','["protesto","impago","plazo"]','es',7),
('COLLECTION','SEND_COLLECTION','REMINDER','RECOMMENDED','Verificar cobro comisiones — #{operationReference}','Confirmar cobro de comisiones de cobranza #{operationReference}.','NORMAL','ROLE_OPERATOR',2,'EVENT_EXECUTION','["comisiones","cobros"]','es',8),
('COLLECTION','SEND_COLLECTION','COMPLIANCE_CHECK','RECOMMENDED','Revisión exposición crediticia','Evaluar exposición por cobranza #{operationReference} de #{formattedAmount} #{currency}.','NORMAL','ROLE_MANAGER',7,'EVENT_EXECUTION','["riesgo","credito"]','es',9),
('COLLECTION','SEND_COLLECTION','TASK','OPTIONAL','Completar expediente digital','Digitalizar documentación de cobranza #{operationReference}.','LOW','ROLE_OPERATOR',5,'EVENT_EXECUTION','["documentacion","archivo"]','es',10),
('COLLECTION','SEND_COLLECTION','FOLLOW_UP','OPTIONAL','Monitoreo riesgo país','Revisar riesgo país para jurisdicción del girado.','LOW','ROLE_MANAGER',10,'EVENT_EXECUTION','["riesgo","pais"]','es',11),
('COLLECTION','SEND_COLLECTION','REMINDER','OPTIONAL','Revisión periódica estado','Revisión periódica de cobranza #{operationReference}.','LOW','ROLE_OPERATOR',-30,'EXPIRY_DATE','["revision","vigencia"]','es',12),
-- Post-emission
('COLLECTION','PRESENT_DRAWEE','FOLLOW_UP','MANDATORY','Seguimiento respuesta del girado','Seguimiento a aceptación/pago del girado para cobranza #{operationReference}. Monto: #{formattedAmount} #{currency}.','HIGH','ROLE_OPERATOR',7,'EVENT_EXECUTION','["seguimiento","girado"]','es',1),
('COLLECTION','ACCEPT','REMINDER','MANDATORY','Monitorear fecha de vencimiento','Seguimiento al vencimiento de aceptación de cobranza #{operationReference}. Verificar pago.','HIGH','ROLE_OPERATOR',5,'EVENT_EXECUTION','["vencimiento","monitoreo"]','es',1),
('COLLECTION','ACCEPT','CLIENT_CONTACT','RECOMMENDED','Notificar aceptación al remitente','Informar a #{applicantName} que girado aceptó cobranza #{operationReference}.','NORMAL','ROLE_OPERATOR',1,'EVENT_EXECUTION','["cliente","notificacion"]','es',2),
('COLLECTION','REFUSE','CLIENT_CONTACT','MANDATORY','Notificar rechazo al remitente','URGENTE: Girado rechazó cobranza #{operationReference}. Solicitar instrucciones a #{applicantName}.','URGENT','ROLE_OPERATOR',0,'EVENT_EXECUTION','["cliente","rechazo","urgente"]','es',1),
('COLLECTION','REFUSE','FOLLOW_UP','MANDATORY','Solicitar instrucciones al remitente','Solicitar a #{applicantName} instrucciones sobre devolución/protesto de cobranza #{operationReference}.','HIGH','ROLE_OPERATOR',2,'EVENT_EXECUTION','["seguimiento","instrucciones"]','es',2),
('COLLECTION','PAYMENT','TASK','MANDATORY','Transferir fondos al remitente','Transferir #{formattedAmount} #{currency} de cobranza #{operationReference} a cuenta de #{applicantName}.','HIGH','ROLE_OPERATOR',1,'EVENT_EXECUTION','["pago","transferencia"]','es',1),
('COLLECTION','PAYMENT','CLIENT_CONTACT','RECOMMENDED','Notificar cobro al remitente','Comunicar a #{applicantName} recepción del pago de cobranza #{operationReference}.','NORMAL','ROLE_OPERATOR',1,'EVENT_EXECUTION','["cliente","pago"]','es',2),
('COLLECTION','RETURN_DOCS','TASK','MANDATORY','Verificar devolución de documentos','Confirmar devolución de documentos de cobranza #{operationReference} al remitente.','HIGH','ROLE_OPERATOR',3,'EVENT_EXECUTION','["documentacion","devolucion"]','es',1),
('COLLECTION','CLOSE','TASK','RECOMMENDED','Reconciliación final de cobranza','Reconciliación de comisiones y gastos de cobranza #{operationReference}.','LOW','ROLE_MANAGER',5,'EVENT_EXECUTION','["contabilidad","cierre"]','es',1);

-- =============================================
-- COLLECTION — EN
-- =============================================
INSERT INTO event_alert_template (operation_type, event_code, alert_type, requirement_level, title_template, description_template, default_priority, assigned_role, due_days_offset, due_date_reference, tags, language, display_order) VALUES
('COLLECTION','SEND_COLLECTION','DEADLINE','MANDATORY','Collection Expiry #{operationReference}','Collection #{operationReference} for #{formattedAmount} #{currency} expires #{expiryDate}. Verify payment/acceptance status.','URGENT','ROLE_OPERATOR',-7,'EXPIRY_DATE','["expiry","critical","urc522"]','en',1),
('COLLECTION','SEND_COLLECTION','FOLLOW_UP','MANDATORY','Drawee Acceptance Follow-up','Follow up on drawee acceptance/payment for collection #{operationReference}.','HIGH','ROLE_OPERATOR',7,'EVENT_EXECUTION','["follow-up","drawee","acceptance"]','en',2),
('COLLECTION','SEND_COLLECTION','COMPLIANCE_CHECK','MANDATORY','KYC/AML Verification — Parties','Compliance check for collection #{operationReference}. Validate sanctions.','HIGH','ROLE_MANAGER',1,'EVENT_EXECUTION','["compliance","kyc","regulatory"]','en',3),
('COLLECTION','SEND_COLLECTION','CLIENT_CONTACT','MANDATORY','Sending Notification to #{applicantName}','Notify #{applicantName} that collection #{operationReference} was sent to collecting bank.','NORMAL','ROLE_OPERATOR',0,'EVENT_EXECUTION','["client","notification"]','en',4),
('COLLECTION','SEND_COLLECTION','FOLLOW_UP','RECOMMENDED','Collecting Bank Acknowledgment','Verify receipt of MT410 from collecting bank for collection #{operationReference}.','NORMAL','ROLE_OPERATOR',5,'EVENT_EXECUTION','["swift","banks","advice"]','en',5),
('COLLECTION','SEND_COLLECTION','TASK','RECOMMENDED','Verify Physical Document Shipment','Confirm physical documents for collection #{operationReference} sent via courier.','NORMAL','ROLE_OPERATOR',1,'EVENT_EXECUTION','["documentation","shipment"]','en',6),
('COLLECTION','SEND_COLLECTION','DEADLINE','RECOMMENDED','Protest Deadline if Unpaid','If drawee does not pay/accept collection #{operationReference}, initiate protest per instructions.','HIGH','ROLE_OPERATOR',-14,'EXPIRY_DATE','["protest","non-payment","deadline"]','en',7),
('COLLECTION','SEND_COLLECTION','REMINDER','RECOMMENDED','Verify Commission Collection — #{operationReference}','Confirm collection #{operationReference} commissions collected.','NORMAL','ROLE_OPERATOR',2,'EVENT_EXECUTION','["commissions","collections"]','en',8),
('COLLECTION','SEND_COLLECTION','COMPLIANCE_CHECK','RECOMMENDED','Credit Exposure Review','Evaluate exposure for collection #{operationReference} of #{formattedAmount} #{currency}.','NORMAL','ROLE_MANAGER',7,'EVENT_EXECUTION','["risk","credit"]','en',9),
('COLLECTION','SEND_COLLECTION','TASK','OPTIONAL','Complete Digital File','Digitize collection #{operationReference} documentation.','LOW','ROLE_OPERATOR',5,'EVENT_EXECUTION','["documentation","archive"]','en',10),
('COLLECTION','SEND_COLLECTION','FOLLOW_UP','OPTIONAL','Country Risk Monitoring','Review country risk for drawee jurisdiction.','LOW','ROLE_MANAGER',10,'EVENT_EXECUTION','["risk","country"]','en',11),
('COLLECTION','SEND_COLLECTION','REMINDER','OPTIONAL','Periodic Status Review','Periodic review of collection #{operationReference}.','LOW','ROLE_OPERATOR',-30,'EXPIRY_DATE','["review","validity"]','en',12),
('COLLECTION','PRESENT_DRAWEE','FOLLOW_UP','MANDATORY','Drawee Response Follow-up','Follow up on drawee acceptance/payment for collection #{operationReference}. Amount: #{formattedAmount} #{currency}.','HIGH','ROLE_OPERATOR',7,'EVENT_EXECUTION','["follow-up","drawee"]','en',1),
('COLLECTION','ACCEPT','REMINDER','MANDATORY','Monitor Maturity Date','Monitor maturity of acceptance for collection #{operationReference}. Verify payment.','HIGH','ROLE_OPERATOR',5,'EVENT_EXECUTION','["expiry","monitoring"]','en',1),
('COLLECTION','REFUSE','CLIENT_CONTACT','MANDATORY','Notify Refusal to Remitter','URGENT: Drawee refused collection #{operationReference}. Request instructions from #{applicantName}.','URGENT','ROLE_OPERATOR',0,'EVENT_EXECUTION','["client","refusal","urgent"]','en',1),
('COLLECTION','REFUSE','FOLLOW_UP','MANDATORY','Request Remitter Instructions','Request instructions from #{applicantName} on return/protest for collection #{operationReference}.','HIGH','ROLE_OPERATOR',2,'EVENT_EXECUTION','["follow-up","instructions"]','en',2),
('COLLECTION','PAYMENT','TASK','MANDATORY','Transfer Funds to Remitter','Transfer #{formattedAmount} #{currency} from collection #{operationReference} to #{applicantName} account.','HIGH','ROLE_OPERATOR',1,'EVENT_EXECUTION','["payment","transfer"]','en',1),
('COLLECTION','RETURN_DOCS','TASK','MANDATORY','Verify Document Return','Confirm documents for collection #{operationReference} returned to remitter.','HIGH','ROLE_OPERATOR',3,'EVENT_EXECUTION','["documentation","return"]','en',1),
('COLLECTION','CLOSE','TASK','RECOMMENDED','Final Collection Reconciliation','Reconcile commissions and expenses for collection #{operationReference}.','LOW','ROLE_MANAGER',5,'EVENT_EXECUTION','["accounting","closure"]','en',1);

-- =============================================
-- STANDBY_LC — ISSUE (Initial) — ES + EN
-- =============================================
INSERT INTO event_alert_template (operation_type, event_code, alert_type, requirement_level, title_template, description_template, default_priority, assigned_role, due_days_offset, due_date_reference, tags, language, display_order) VALUES
('STANDBY_LC','ISSUE','DEADLINE','MANDATORY','Vencimiento Standby LC #{operationReference}','Standby LC #{operationReference} por #{formattedAmount} #{currency} vence el #{expiryDate}.','URGENT','ROLE_OPERATOR',-7,'EXPIRY_DATE','["vencimiento","critico","isp98"]','es',1),
('STANDBY_LC','ISSUE','DEADLINE','MANDATORY','Período de demanda — #{operationReference}','Verificar demand period de Standby LC #{operationReference}. Beneficiario puede reclamar hasta vencimiento.','HIGH','ROLE_OPERATOR',-15,'EXPIRY_DATE','["demanda","plazo","isp98"]','es',2),
('STANDBY_LC','ISSUE','COMPLIANCE_CHECK','MANDATORY','Verificación KYC/AML — #{applicantName} / #{beneficiaryName}','Verificación compliance para Standby LC #{operationReference}.','HIGH','ROLE_MANAGER',1,'EVENT_EXECUTION','["compliance","kyc","regulatorio"]','es',3),
('STANDBY_LC','ISSUE','CLIENT_CONTACT','MANDATORY','Notificación emisión a #{applicantName}','Notificar a #{applicantName} emisión de Standby LC #{operationReference} a favor de #{beneficiaryName}.','NORMAL','ROLE_OPERATOR',0,'EVENT_EXECUTION','["cliente","notificacion","emision"]','es',4),
('STANDBY_LC','ISSUE','FOLLOW_UP','RECOMMENDED','Verificar contragarantía','Verificar contragarantía válida para Standby LC #{operationReference}.','NORMAL','ROLE_OPERATOR',5,'EVENT_EXECUTION','["contragarantia","verificacion"]','es',5),
('STANDBY_LC','ISSUE','TASK','RECOMMENDED','Provisión de fondos #{formattedAmount}','Verificar provisión para Standby LC #{operationReference} por #{formattedAmount} #{currency}.','HIGH','ROLE_MANAGER',3,'EVENT_EXECUTION','["fondos","tesoreria"]','es',6),
('STANDBY_LC','ISSUE','COMPLIANCE_CHECK','RECOMMENDED','Revisión exposición crediticia','Evaluar exposición de #{applicantName} con Standby LC #{operationReference}.','NORMAL','ROLE_MANAGER',7,'EVENT_EXECUTION','["riesgo","credito","exposicion"]','es',7),
('STANDBY_LC','ISSUE','REMINDER','RECOMMENDED','Verificar cobro comisiones','Confirmar cobro de comisiones de Standby LC #{operationReference}.','NORMAL','ROLE_OPERATOR',2,'EVENT_EXECUTION','["comisiones","cobros"]','es',8),
('STANDBY_LC','ISSUE','FOLLOW_UP','RECOMMENDED','Seguimiento acuse MT760','Verificar acuse de recepción para Standby LC #{operationReference}.','NORMAL','ROLE_OPERATOR',5,'EVENT_EXECUTION','["swift","bancos"]','es',9),
('STANDBY_LC','ISSUE','TASK','OPTIONAL','Completar expediente digital','Digitalizar documentación de Standby LC #{operationReference}.','LOW','ROLE_OPERATOR',5,'EVENT_EXECUTION','["documentacion","archivo"]','es',10),
('STANDBY_LC','ISSUE','FOLLOW_UP','OPTIONAL','Monitoreo riesgo país','Revisar riesgo país para #{beneficiaryName}.','LOW','ROLE_MANAGER',10,'EVENT_EXECUTION','["riesgo","pais"]','es',11),
('STANDBY_LC','ISSUE','REMINDER','OPTIONAL','Revisión periódica vigencia','Revisión periódica de Standby LC #{operationReference}.','LOW','ROLE_OPERATOR',-60,'EXPIRY_DATE','["revision","vigencia"]','es',12),
-- EN
('STANDBY_LC','ISSUE','DEADLINE','MANDATORY','Standby LC Expiry #{operationReference}','Standby LC #{operationReference} for #{formattedAmount} #{currency} expires #{expiryDate}.','URGENT','ROLE_OPERATOR',-7,'EXPIRY_DATE','["expiry","critical","isp98"]','en',1),
('STANDBY_LC','ISSUE','DEADLINE','MANDATORY','Demand Period — #{operationReference}','Verify demand period for Standby LC #{operationReference}. Beneficiary may claim until expiry.','HIGH','ROLE_OPERATOR',-15,'EXPIRY_DATE','["demand","deadline","isp98"]','en',2),
('STANDBY_LC','ISSUE','COMPLIANCE_CHECK','MANDATORY','KYC/AML Verification — #{applicantName} / #{beneficiaryName}','Compliance check for Standby LC #{operationReference}.','HIGH','ROLE_MANAGER',1,'EVENT_EXECUTION','["compliance","kyc","regulatory"]','en',3),
('STANDBY_LC','ISSUE','CLIENT_CONTACT','MANDATORY','Issuance Notification to #{applicantName}','Notify #{applicantName} of Standby LC #{operationReference} issuance in favor of #{beneficiaryName}.','NORMAL','ROLE_OPERATOR',0,'EVENT_EXECUTION','["client","notification","issuance"]','en',4),
('STANDBY_LC','ISSUE','FOLLOW_UP','RECOMMENDED','Verify Counter-Guarantee','Verify valid counter-guarantee for Standby LC #{operationReference}.','NORMAL','ROLE_OPERATOR',5,'EVENT_EXECUTION','["counter-guarantee","verification"]','en',5),
('STANDBY_LC','ISSUE','TASK','RECOMMENDED','Fund Provision #{formattedAmount}','Verify fund provision for Standby LC #{operationReference} of #{formattedAmount} #{currency}.','HIGH','ROLE_MANAGER',3,'EVENT_EXECUTION','["funds","treasury"]','en',6),
('STANDBY_LC','ISSUE','COMPLIANCE_CHECK','RECOMMENDED','Credit Exposure Review','Evaluate #{applicantName} exposure with Standby LC #{operationReference}.','NORMAL','ROLE_MANAGER',7,'EVENT_EXECUTION','["risk","credit","exposure"]','en',7),
('STANDBY_LC','ISSUE','REMINDER','RECOMMENDED','Verify Commission Collection','Confirm Standby LC #{operationReference} commissions collected.','NORMAL','ROLE_OPERATOR',2,'EVENT_EXECUTION','["commissions","collections"]','en',8),
('STANDBY_LC','ISSUE','FOLLOW_UP','RECOMMENDED','MT760 Acknowledgment Follow-up','Verify acknowledgment for Standby LC #{operationReference}.','NORMAL','ROLE_OPERATOR',5,'EVENT_EXECUTION','["swift","banks"]','en',9),
('STANDBY_LC','ISSUE','TASK','OPTIONAL','Complete Digital File','Digitize Standby LC #{operationReference} documentation.','LOW','ROLE_OPERATOR',5,'EVENT_EXECUTION','["documentation","archive"]','en',10),
('STANDBY_LC','ISSUE','FOLLOW_UP','OPTIONAL','Country Risk Monitoring','Review country risk for #{beneficiaryName}.','LOW','ROLE_MANAGER',10,'EVENT_EXECUTION','["risk","country"]','en',11),
('STANDBY_LC','ISSUE','REMINDER','OPTIONAL','Periodic Validity Review','Periodic review of Standby LC #{operationReference}.','LOW','ROLE_OPERATOR',-60,'EXPIRY_DATE','["review","validity"]','en',12);

-- =============================================
-- COLLECTION_IMPORT — RECEIVE_COLLECTION (Initial) — ES + EN
-- =============================================
INSERT INTO event_alert_template (operation_type, event_code, alert_type, requirement_level, title_template, description_template, default_priority, assigned_role, due_days_offset, due_date_reference, tags, language, display_order) VALUES
('COLLECTION_IMPORT','RECEIVE_COLLECTION','DEADLINE','MANDATORY','Vencimiento Cobranza Import #{operationReference}','Cobranza import #{operationReference} por #{formattedAmount} #{currency} vence el #{expiryDate}. Verificar presentación al girado.','URGENT','ROLE_OPERATOR',-7,'EXPIRY_DATE','["vencimiento","critico","urc522"]','es',1),
('COLLECTION_IMPORT','RECEIVE_COLLECTION','FOLLOW_UP','MANDATORY','Plazo presentación al girado','Presentar documentos de cobranza #{operationReference} al girado dentro del plazo establecido.','HIGH','ROLE_OPERATOR',3,'EVENT_EXECUTION','["girado","presentacion","plazo"]','es',2),
('COLLECTION_IMPORT','RECEIVE_COLLECTION','COMPLIANCE_CHECK','MANDATORY','Verificación KYC/AML — partes','Verificación compliance para cobranza import #{operationReference}.','HIGH','ROLE_MANAGER',1,'EVENT_EXECUTION','["compliance","kyc","regulatorio"]','es',3),
('COLLECTION_IMPORT','RECEIVE_COLLECTION','CLIENT_CONTACT','MANDATORY','Notificar recepción al girado','Notificar al girado la recepción de cobranza #{operationReference} por #{formattedAmount} #{currency}.','NORMAL','ROLE_OPERATOR',0,'EVENT_EXECUTION','["cliente","notificacion"]','es',4),
('COLLECTION_IMPORT','RECEIVE_COLLECTION','FOLLOW_UP','RECOMMENDED','Seguimiento aceptación girado','Seguimiento a aceptación/pago del girado para cobranza import #{operationReference}.','NORMAL','ROLE_OPERATOR',7,'EVENT_EXECUTION','["seguimiento","girado"]','es',5),
('COLLECTION_IMPORT','RECEIVE_COLLECTION','REMINDER','RECOMMENDED','Verificar cobro comisiones','Confirmar cobro de comisiones de cobranza import #{operationReference}.','NORMAL','ROLE_OPERATOR',2,'EVENT_EXECUTION','["comisiones","cobros"]','es',6),
('COLLECTION_IMPORT','RECEIVE_COLLECTION','TASK','RECOMMENDED','Verificar documentos recibidos','Verificar integridad de documentos recibidos para cobranza #{operationReference}.','NORMAL','ROLE_OPERATOR',1,'EVENT_EXECUTION','["documentacion","verificacion"]','es',7),
('COLLECTION_IMPORT','RECEIVE_COLLECTION','COMPLIANCE_CHECK','RECOMMENDED','Revisión exposición crediticia','Evaluar exposición por cobranza import #{operationReference}.','NORMAL','ROLE_MANAGER',7,'EVENT_EXECUTION','["riesgo","credito"]','es',8),
('COLLECTION_IMPORT','RECEIVE_COLLECTION','DEADLINE','RECOMMENDED','Plazo protesto si impago','Iniciar protesto si girado no paga/acepta cobranza #{operationReference}.','HIGH','ROLE_OPERATOR',-14,'EXPIRY_DATE','["protesto","impago"]','es',9),
('COLLECTION_IMPORT','RECEIVE_COLLECTION','TASK','OPTIONAL','Completar expediente digital','Digitalizar documentación de cobranza import #{operationReference}.','LOW','ROLE_OPERATOR',5,'EVENT_EXECUTION','["documentacion","archivo"]','es',10),
('COLLECTION_IMPORT','RECEIVE_COLLECTION','FOLLOW_UP','OPTIONAL','Monitoreo riesgo país','Revisar riesgo país para jurisdicción del remitente.','LOW','ROLE_MANAGER',10,'EVENT_EXECUTION','["riesgo","pais"]','es',11),
('COLLECTION_IMPORT','RECEIVE_COLLECTION','REMINDER','OPTIONAL','Revisión periódica estado','Revisión periódica de cobranza import #{operationReference}.','LOW','ROLE_OPERATOR',-30,'EXPIRY_DATE','["revision","vigencia"]','es',12),
-- EN
('COLLECTION_IMPORT','RECEIVE_COLLECTION','DEADLINE','MANDATORY','Import Collection Expiry #{operationReference}','Import collection #{operationReference} for #{formattedAmount} #{currency} expires #{expiryDate}. Verify drawee presentation.','URGENT','ROLE_OPERATOR',-7,'EXPIRY_DATE','["expiry","critical","urc522"]','en',1),
('COLLECTION_IMPORT','RECEIVE_COLLECTION','FOLLOW_UP','MANDATORY','Drawee Presentation Deadline','Present collection #{operationReference} documents to drawee within established deadline.','HIGH','ROLE_OPERATOR',3,'EVENT_EXECUTION','["drawee","presentation","deadline"]','en',2),
('COLLECTION_IMPORT','RECEIVE_COLLECTION','COMPLIANCE_CHECK','MANDATORY','KYC/AML Verification — Parties','Compliance check for import collection #{operationReference}.','HIGH','ROLE_MANAGER',1,'EVENT_EXECUTION','["compliance","kyc","regulatory"]','en',3),
('COLLECTION_IMPORT','RECEIVE_COLLECTION','CLIENT_CONTACT','MANDATORY','Notify Drawee of Receipt','Notify drawee of import collection #{operationReference} for #{formattedAmount} #{currency}.','NORMAL','ROLE_OPERATOR',0,'EVENT_EXECUTION','["client","notification"]','en',4),
('COLLECTION_IMPORT','RECEIVE_COLLECTION','FOLLOW_UP','RECOMMENDED','Drawee Acceptance Follow-up','Follow up on drawee acceptance/payment for import collection #{operationReference}.','NORMAL','ROLE_OPERATOR',7,'EVENT_EXECUTION','["follow-up","drawee"]','en',5),
('COLLECTION_IMPORT','RECEIVE_COLLECTION','REMINDER','RECOMMENDED','Verify Commission Collection','Confirm import collection #{operationReference} commissions collected.','NORMAL','ROLE_OPERATOR',2,'EVENT_EXECUTION','["commissions","collections"]','en',6),
('COLLECTION_IMPORT','RECEIVE_COLLECTION','TASK','RECOMMENDED','Verify Received Documents','Verify integrity of documents received for collection #{operationReference}.','NORMAL','ROLE_OPERATOR',1,'EVENT_EXECUTION','["documentation","verification"]','en',7),
('COLLECTION_IMPORT','RECEIVE_COLLECTION','COMPLIANCE_CHECK','RECOMMENDED','Credit Exposure Review','Evaluate exposure for import collection #{operationReference}.','NORMAL','ROLE_MANAGER',7,'EVENT_EXECUTION','["risk","credit"]','en',8),
('COLLECTION_IMPORT','RECEIVE_COLLECTION','DEADLINE','RECOMMENDED','Protest Deadline if Unpaid','Initiate protest if drawee does not pay/accept collection #{operationReference}.','HIGH','ROLE_OPERATOR',-14,'EXPIRY_DATE','["protest","non-payment"]','en',9),
('COLLECTION_IMPORT','RECEIVE_COLLECTION','TASK','OPTIONAL','Complete Digital File','Digitize import collection #{operationReference} documentation.','LOW','ROLE_OPERATOR',5,'EVENT_EXECUTION','["documentation","archive"]','en',10),
('COLLECTION_IMPORT','RECEIVE_COLLECTION','FOLLOW_UP','OPTIONAL','Country Risk Monitoring','Review country risk for remitter jurisdiction.','LOW','ROLE_MANAGER',10,'EVENT_EXECUTION','["risk","country"]','en',11),
('COLLECTION_IMPORT','RECEIVE_COLLECTION','REMINDER','OPTIONAL','Periodic Status Review','Periodic review of import collection #{operationReference}.','LOW','ROLE_OPERATOR',-30,'EXPIRY_DATE','["review","validity"]','en',12);

-- =============================================
-- COLLECTION_EXPORT — SEND_COLLECTION (Initial) — ES + EN
-- =============================================
INSERT INTO event_alert_template (operation_type, event_code, alert_type, requirement_level, title_template, description_template, default_priority, assigned_role, due_days_offset, due_date_reference, tags, language, display_order) VALUES
('COLLECTION_EXPORT','SEND_COLLECTION','DEADLINE','MANDATORY','Vencimiento Cobranza Export #{operationReference}','Cobranza export #{operationReference} por #{formattedAmount} #{currency} vence el #{expiryDate}.','URGENT','ROLE_OPERATOR',-7,'EXPIRY_DATE','["vencimiento","critico","urc522"]','es',1),
('COLLECTION_EXPORT','SEND_COLLECTION','FOLLOW_UP','MANDATORY','Seguimiento cobro exterior','Seguimiento al cobro en el exterior de cobranza export #{operationReference}.','HIGH','ROLE_OPERATOR',7,'EVENT_EXECUTION','["seguimiento","cobro","exterior"]','es',2),
('COLLECTION_EXPORT','SEND_COLLECTION','COMPLIANCE_CHECK','MANDATORY','Verificación KYC/AML — partes','Verificación compliance para cobranza export #{operationReference}.','HIGH','ROLE_MANAGER',1,'EVENT_EXECUTION','["compliance","kyc","regulatorio"]','es',3),
('COLLECTION_EXPORT','SEND_COLLECTION','CLIENT_CONTACT','MANDATORY','Notificar envío a #{applicantName}','Notificar a #{applicantName} envío de cobranza export #{operationReference}.','NORMAL','ROLE_OPERATOR',0,'EVENT_EXECUTION','["cliente","notificacion"]','es',4),
('COLLECTION_EXPORT','SEND_COLLECTION','FOLLOW_UP','RECOMMENDED','Seguimiento acuse banco cobrador','Verificar acuse del banco cobrador para cobranza export #{operationReference}.','NORMAL','ROLE_OPERATOR',5,'EVENT_EXECUTION','["swift","bancos"]','es',5),
('COLLECTION_EXPORT','SEND_COLLECTION','TASK','RECOMMENDED','Verificar envío documentos','Confirmar envío documentos de cobranza export #{operationReference} por courier.','NORMAL','ROLE_OPERATOR',1,'EVENT_EXECUTION','["documentacion","envio"]','es',6),
('COLLECTION_EXPORT','SEND_COLLECTION','DEADLINE','RECOMMENDED','Plazo protesto si impago','Iniciar protesto si impago de cobranza export #{operationReference}.','HIGH','ROLE_OPERATOR',-14,'EXPIRY_DATE','["protesto","impago"]','es',7),
('COLLECTION_EXPORT','SEND_COLLECTION','REMINDER','RECOMMENDED','Verificar cobro comisiones','Confirmar cobro comisiones de cobranza export #{operationReference}.','NORMAL','ROLE_OPERATOR',2,'EVENT_EXECUTION','["comisiones","cobros"]','es',8),
('COLLECTION_EXPORT','SEND_COLLECTION','FOLLOW_UP','RECOMMENDED','Seguimiento remesa de fondos','Seguimiento a remesa de fondos de cobranza export #{operationReference}.','NORMAL','ROLE_OPERATOR',14,'EVENT_EXECUTION','["remesa","fondos"]','es',9),
('COLLECTION_EXPORT','SEND_COLLECTION','TASK','OPTIONAL','Completar expediente digital','Digitalizar documentación de cobranza export #{operationReference}.','LOW','ROLE_OPERATOR',5,'EVENT_EXECUTION','["documentacion","archivo"]','es',10),
('COLLECTION_EXPORT','SEND_COLLECTION','FOLLOW_UP','OPTIONAL','Monitoreo riesgo país','Revisar riesgo país para jurisdicción del girado.','LOW','ROLE_MANAGER',10,'EVENT_EXECUTION','["riesgo","pais"]','es',11),
('COLLECTION_EXPORT','SEND_COLLECTION','REMINDER','OPTIONAL','Revisión periódica estado','Revisión periódica de cobranza export #{operationReference}.','LOW','ROLE_OPERATOR',-30,'EXPIRY_DATE','["revision","vigencia"]','es',12),
-- EN
('COLLECTION_EXPORT','SEND_COLLECTION','DEADLINE','MANDATORY','Export Collection Expiry #{operationReference}','Export collection #{operationReference} for #{formattedAmount} #{currency} expires #{expiryDate}.','URGENT','ROLE_OPERATOR',-7,'EXPIRY_DATE','["expiry","critical","urc522"]','en',1),
('COLLECTION_EXPORT','SEND_COLLECTION','FOLLOW_UP','MANDATORY','Foreign Collection Follow-up','Follow up on foreign collection payment for export collection #{operationReference}.','HIGH','ROLE_OPERATOR',7,'EVENT_EXECUTION','["follow-up","collection","foreign"]','en',2),
('COLLECTION_EXPORT','SEND_COLLECTION','COMPLIANCE_CHECK','MANDATORY','KYC/AML Verification — Parties','Compliance check for export collection #{operationReference}.','HIGH','ROLE_MANAGER',1,'EVENT_EXECUTION','["compliance","kyc","regulatory"]','en',3),
('COLLECTION_EXPORT','SEND_COLLECTION','CLIENT_CONTACT','MANDATORY','Notify Sending to #{applicantName}','Notify #{applicantName} of export collection #{operationReference} sending.','NORMAL','ROLE_OPERATOR',0,'EVENT_EXECUTION','["client","notification"]','en',4),
('COLLECTION_EXPORT','SEND_COLLECTION','FOLLOW_UP','RECOMMENDED','Collecting Bank Acknowledgment','Verify collecting bank acknowledgment for export collection #{operationReference}.','NORMAL','ROLE_OPERATOR',5,'EVENT_EXECUTION','["swift","banks"]','en',5),
('COLLECTION_EXPORT','SEND_COLLECTION','TASK','RECOMMENDED','Verify Document Shipment','Confirm export collection #{operationReference} documents sent via courier.','NORMAL','ROLE_OPERATOR',1,'EVENT_EXECUTION','["documentation","shipment"]','en',6),
('COLLECTION_EXPORT','SEND_COLLECTION','DEADLINE','RECOMMENDED','Protest Deadline if Unpaid','Initiate protest if export collection #{operationReference} unpaid.','HIGH','ROLE_OPERATOR',-14,'EXPIRY_DATE','["protest","non-payment"]','en',7),
('COLLECTION_EXPORT','SEND_COLLECTION','REMINDER','RECOMMENDED','Verify Commission Collection','Confirm export collection #{operationReference} commissions collected.','NORMAL','ROLE_OPERATOR',2,'EVENT_EXECUTION','["commissions","collections"]','en',8),
('COLLECTION_EXPORT','SEND_COLLECTION','FOLLOW_UP','RECOMMENDED','Proceeds Remittance Follow-up','Follow up on proceeds remittance for export collection #{operationReference}.','NORMAL','ROLE_OPERATOR',14,'EVENT_EXECUTION','["remittance","funds"]','en',9),
('COLLECTION_EXPORT','SEND_COLLECTION','TASK','OPTIONAL','Complete Digital File','Digitize export collection #{operationReference} documentation.','LOW','ROLE_OPERATOR',5,'EVENT_EXECUTION','["documentation","archive"]','en',10),
('COLLECTION_EXPORT','SEND_COLLECTION','FOLLOW_UP','OPTIONAL','Country Risk Monitoring','Review country risk for drawee jurisdiction.','LOW','ROLE_MANAGER',10,'EVENT_EXECUTION','["risk","country"]','en',11),
('COLLECTION_EXPORT','SEND_COLLECTION','REMINDER','OPTIONAL','Periodic Status Review','Periodic review of export collection #{operationReference}.','LOW','ROLE_OPERATOR',-30,'EXPIRY_DATE','["review","validity"]','en',12);

-- =============================================
-- GUARANTEE_MANDATARIA — RECEIVE_MANDATE (Initial) — ES + EN
-- =============================================
INSERT INTO event_alert_template (operation_type, event_code, alert_type, requirement_level, title_template, description_template, default_priority, assigned_role, due_days_offset, due_date_reference, tags, language, display_order) VALUES
('GUARANTEE_MANDATARIA','RECEIVE_MANDATE','DEADLINE','MANDATORY','Plazo emisión post-mandato #{operationReference}','Emitir garantía dentro del plazo establecido en mandato #{operationReference}. Monto: #{formattedAmount} #{currency}.','URGENT','ROLE_OPERATOR',5,'EVENT_EXECUTION','["plazo","emision","mandato"]','es',1),
('GUARANTEE_MANDATARIA','RECEIVE_MANDATE','DEADLINE','MANDATORY','Vencimiento Garantía Mandataria #{operationReference}','Garantía mandataria #{operationReference} vence el #{expiryDate}. Monitorear estado.','HIGH','ROLE_OPERATOR',-7,'EXPIRY_DATE','["vencimiento","critico"]','es',2),
('GUARANTEE_MANDATARIA','RECEIVE_MANDATE','COMPLIANCE_CHECK','MANDATORY','Verificación KYC/AML — mandante','Verificación compliance del mandante para garantía #{operationReference}.','HIGH','ROLE_MANAGER',1,'EVENT_EXECUTION','["compliance","kyc","regulatorio"]','es',3),
('GUARANTEE_MANDATARIA','RECEIVE_MANDATE','TASK','MANDATORY','Verificar mandato recibido','Verificar integridad y autenticidad del mandato #{operationReference} recibido.','HIGH','ROLE_OPERATOR',1,'EVENT_EXECUTION','["mandato","verificacion"]','es',4),
('GUARANTEE_MANDATARIA','RECEIVE_MANDATE','FOLLOW_UP','RECOMMENDED','Seguimiento emisión garantía','Seguimiento a emisión de garantía bajo mandato #{operationReference}.','NORMAL','ROLE_OPERATOR',3,'EVENT_EXECUTION','["seguimiento","emision"]','es',5),
('GUARANTEE_MANDATARIA','RECEIVE_MANDATE','REMINDER','RECOMMENDED','Verificar cobro comisiones','Confirmar cobro de comisiones de garantía mandataria #{operationReference}.','NORMAL','ROLE_OPERATOR',2,'EVENT_EXECUTION','["comisiones","cobros"]','es',6),
('GUARANTEE_MANDATARIA','RECEIVE_MANDATE','COMPLIANCE_CHECK','RECOMMENDED','Revisión exposición crediticia','Evaluar exposición por garantía mandataria #{operationReference}.','NORMAL','ROLE_MANAGER',7,'EVENT_EXECUTION','["riesgo","credito"]','es',7),
('GUARANTEE_MANDATARIA','RECEIVE_MANDATE','CLIENT_CONTACT','RECOMMENDED','Notificar recepción de mandato','Confirmar al mandante recepción de mandato #{operationReference}.','NORMAL','ROLE_OPERATOR',0,'EVENT_EXECUTION','["cliente","notificacion"]','es',8),
('GUARANTEE_MANDATARIA','RECEIVE_MANDATE','FOLLOW_UP','RECOMMENDED','Verificar contragarantía','Verificar contragarantía para mandato #{operationReference}.','NORMAL','ROLE_OPERATOR',5,'EVENT_EXECUTION','["contragarantia","verificacion"]','es',9),
('GUARANTEE_MANDATARIA','RECEIVE_MANDATE','TASK','OPTIONAL','Completar expediente digital','Digitalizar documentación de mandato #{operationReference}.','LOW','ROLE_OPERATOR',5,'EVENT_EXECUTION','["documentacion","archivo"]','es',10),
('GUARANTEE_MANDATARIA','RECEIVE_MANDATE','FOLLOW_UP','OPTIONAL','Monitoreo riesgo país','Revisar riesgo país para jurisdicción del mandante.','LOW','ROLE_MANAGER',10,'EVENT_EXECUTION','["riesgo","pais"]','es',11),
('GUARANTEE_MANDATARIA','RECEIVE_MANDATE','REMINDER','OPTIONAL','Revisión periódica vigencia','Revisión periódica de garantía mandataria #{operationReference}.','LOW','ROLE_OPERATOR',-60,'EXPIRY_DATE','["revision","vigencia"]','es',12),
-- EN
('GUARANTEE_MANDATARIA','RECEIVE_MANDATE','DEADLINE','MANDATORY','Post-Mandate Issuance Deadline #{operationReference}','Issue guarantee within mandate #{operationReference} deadline. Amount: #{formattedAmount} #{currency}.','URGENT','ROLE_OPERATOR',5,'EVENT_EXECUTION','["deadline","issuance","mandate"]','en',1),
('GUARANTEE_MANDATARIA','RECEIVE_MANDATE','DEADLINE','MANDATORY','Mandated Guarantee Expiry #{operationReference}','Mandated guarantee #{operationReference} expires #{expiryDate}. Monitor status.','HIGH','ROLE_OPERATOR',-7,'EXPIRY_DATE','["expiry","critical"]','en',2),
('GUARANTEE_MANDATARIA','RECEIVE_MANDATE','COMPLIANCE_CHECK','MANDATORY','KYC/AML Verification — Mandator','Compliance check for mandate #{operationReference} mandator.','HIGH','ROLE_MANAGER',1,'EVENT_EXECUTION','["compliance","kyc","regulatory"]','en',3),
('GUARANTEE_MANDATARIA','RECEIVE_MANDATE','TASK','MANDATORY','Verify Received Mandate','Verify integrity and authenticity of mandate #{operationReference}.','HIGH','ROLE_OPERATOR',1,'EVENT_EXECUTION','["mandate","verification"]','en',4),
('GUARANTEE_MANDATARIA','RECEIVE_MANDATE','FOLLOW_UP','RECOMMENDED','Guarantee Issuance Follow-up','Follow up on guarantee issuance under mandate #{operationReference}.','NORMAL','ROLE_OPERATOR',3,'EVENT_EXECUTION','["follow-up","issuance"]','en',5),
('GUARANTEE_MANDATARIA','RECEIVE_MANDATE','REMINDER','RECOMMENDED','Verify Commission Collection','Confirm mandated guarantee #{operationReference} commissions collected.','NORMAL','ROLE_OPERATOR',2,'EVENT_EXECUTION','["commissions","collections"]','en',6),
('GUARANTEE_MANDATARIA','RECEIVE_MANDATE','COMPLIANCE_CHECK','RECOMMENDED','Credit Exposure Review','Evaluate exposure for mandated guarantee #{operationReference}.','NORMAL','ROLE_MANAGER',7,'EVENT_EXECUTION','["risk","credit"]','en',7),
('GUARANTEE_MANDATARIA','RECEIVE_MANDATE','CLIENT_CONTACT','RECOMMENDED','Notify Mandate Receipt','Confirm mandate #{operationReference} receipt to mandator.','NORMAL','ROLE_OPERATOR',0,'EVENT_EXECUTION','["client","notification"]','en',8),
('GUARANTEE_MANDATARIA','RECEIVE_MANDATE','FOLLOW_UP','RECOMMENDED','Verify Counter-Guarantee','Verify counter-guarantee for mandate #{operationReference}.','NORMAL','ROLE_OPERATOR',5,'EVENT_EXECUTION','["counter-guarantee","verification"]','en',9),
('GUARANTEE_MANDATARIA','RECEIVE_MANDATE','TASK','OPTIONAL','Complete Digital File','Digitize mandate #{operationReference} documentation.','LOW','ROLE_OPERATOR',5,'EVENT_EXECUTION','["documentation","archive"]','en',10),
('GUARANTEE_MANDATARIA','RECEIVE_MANDATE','FOLLOW_UP','OPTIONAL','Country Risk Monitoring','Review country risk for mandator jurisdiction.','LOW','ROLE_MANAGER',10,'EVENT_EXECUTION','["risk","country"]','en',11),
('GUARANTEE_MANDATARIA','RECEIVE_MANDATE','REMINDER','OPTIONAL','Periodic Validity Review','Periodic review of mandated guarantee #{operationReference}.','LOW','ROLE_OPERATOR',-60,'EXPIRY_DATE','["review","validity"]','en',12);

-- =============================================
-- TRADE_FINANCING — CREATE_FINANCING (Initial) — ES + EN
-- =============================================
INSERT INTO event_alert_template (operation_type, event_code, alert_type, requirement_level, title_template, description_template, default_priority, assigned_role, due_days_offset, due_date_reference, tags, language, display_order) VALUES
('TRADE_FINANCING','CREATE_FINANCING','DEADLINE','MANDATORY','Vencimiento Financiamiento #{operationReference}','Financiamiento #{operationReference} por #{formattedAmount} #{currency} vence el #{expiryDate}. Verificar pago/rollover.','URGENT','ROLE_OPERATOR',-7,'EXPIRY_DATE','["vencimiento","critico"]','es',1),
('TRADE_FINANCING','CREATE_FINANCING','TASK','MANDATORY','Calendario de pagos — #{operationReference}','Configurar calendario de pagos para financiamiento #{operationReference}. Monto: #{formattedAmount} #{currency}.','HIGH','ROLE_OPERATOR',1,'EVENT_EXECUTION','["pagos","calendario"]','es',2),
('TRADE_FINANCING','CREATE_FINANCING','COMPLIANCE_CHECK','MANDATORY','Verificación KYC/AML — #{applicantName}','Verificación compliance para financiamiento #{operationReference} de #{applicantName}.','HIGH','ROLE_MANAGER',1,'EVENT_EXECUTION','["compliance","kyc","regulatorio"]','es',3),
('TRADE_FINANCING','CREATE_FINANCING','CLIENT_CONTACT','MANDATORY','Notificación creación a #{applicantName}','Notificar a #{applicantName} creación de financiamiento #{operationReference}.','NORMAL','ROLE_OPERATOR',0,'EVENT_EXECUTION','["cliente","notificacion"]','es',4),
('TRADE_FINANCING','CREATE_FINANCING','TASK','RECOMMENDED','Revisión garantías colaterales','Verificar garantías colaterales para financiamiento #{operationReference}.','NORMAL','ROLE_OPERATOR',5,'EVENT_EXECUTION','["garantias","colateral"]','es',5),
('TRADE_FINANCING','CREATE_FINANCING','REMINDER','RECOMMENDED','Verificar cobro comisiones','Confirmar cobro comisiones de financiamiento #{operationReference}.','NORMAL','ROLE_OPERATOR',2,'EVENT_EXECUTION','["comisiones","cobros"]','es',6),
('TRADE_FINANCING','CREATE_FINANCING','COMPLIANCE_CHECK','RECOMMENDED','Revisión exposición crediticia','Evaluar exposición de #{applicantName} con financiamiento #{operationReference}.','NORMAL','ROLE_MANAGER',7,'EVENT_EXECUTION','["riesgo","credito"]','es',7),
('TRADE_FINANCING','CREATE_FINANCING','FOLLOW_UP','RECOMMENDED','Seguimiento desembolso','Verificar desembolso de fondos de financiamiento #{operationReference}.','NORMAL','ROLE_OPERATOR',3,'EVENT_EXECUTION','["desembolso","seguimiento"]','es',8),
('TRADE_FINANCING','CREATE_FINANCING','REMINDER','RECOMMENDED','Evaluación rollover pre-vencimiento','Evaluar posibilidad de rollover de financiamiento #{operationReference} antes del vencimiento.','NORMAL','ROLE_MANAGER',-30,'EXPIRY_DATE','["rollover","vencimiento"]','es',9),
('TRADE_FINANCING','CREATE_FINANCING','TASK','OPTIONAL','Completar expediente digital','Digitalizar documentación de financiamiento #{operationReference}.','LOW','ROLE_OPERATOR',5,'EVENT_EXECUTION','["documentacion","archivo"]','es',10),
('TRADE_FINANCING','CREATE_FINANCING','FOLLOW_UP','OPTIONAL','Monitoreo riesgo país','Revisar riesgo país para #{applicantName}.','LOW','ROLE_MANAGER',10,'EVENT_EXECUTION','["riesgo","pais"]','es',11),
('TRADE_FINANCING','CREATE_FINANCING','REMINDER','OPTIONAL','Revisión periódica estado','Revisión periódica de financiamiento #{operationReference}.','LOW','ROLE_OPERATOR',-60,'EXPIRY_DATE','["revision","vigencia"]','es',12),
-- EN
('TRADE_FINANCING','CREATE_FINANCING','DEADLINE','MANDATORY','Financing Maturity #{operationReference}','Financing #{operationReference} for #{formattedAmount} #{currency} matures #{expiryDate}. Verify payment/rollover.','URGENT','ROLE_OPERATOR',-7,'EXPIRY_DATE','["maturity","critical"]','en',1),
('TRADE_FINANCING','CREATE_FINANCING','TASK','MANDATORY','Payment Schedule — #{operationReference}','Configure payment schedule for financing #{operationReference}. Amount: #{formattedAmount} #{currency}.','HIGH','ROLE_OPERATOR',1,'EVENT_EXECUTION','["payments","schedule"]','en',2),
('TRADE_FINANCING','CREATE_FINANCING','COMPLIANCE_CHECK','MANDATORY','KYC/AML Verification — #{applicantName}','Compliance check for financing #{operationReference} of #{applicantName}.','HIGH','ROLE_MANAGER',1,'EVENT_EXECUTION','["compliance","kyc","regulatory"]','en',3),
('TRADE_FINANCING','CREATE_FINANCING','CLIENT_CONTACT','MANDATORY','Creation Notification to #{applicantName}','Notify #{applicantName} of financing #{operationReference} creation.','NORMAL','ROLE_OPERATOR',0,'EVENT_EXECUTION','["client","notification"]','en',4),
('TRADE_FINANCING','CREATE_FINANCING','TASK','RECOMMENDED','Collateral Review','Verify collateral guarantees for financing #{operationReference}.','NORMAL','ROLE_OPERATOR',5,'EVENT_EXECUTION','["guarantees","collateral"]','en',5),
('TRADE_FINANCING','CREATE_FINANCING','REMINDER','RECOMMENDED','Verify Commission Collection','Confirm financing #{operationReference} commissions collected.','NORMAL','ROLE_OPERATOR',2,'EVENT_EXECUTION','["commissions","collections"]','en',6),
('TRADE_FINANCING','CREATE_FINANCING','COMPLIANCE_CHECK','RECOMMENDED','Credit Exposure Review','Evaluate #{applicantName} exposure with financing #{operationReference}.','NORMAL','ROLE_MANAGER',7,'EVENT_EXECUTION','["risk","credit"]','en',7),
('TRADE_FINANCING','CREATE_FINANCING','FOLLOW_UP','RECOMMENDED','Disbursement Follow-up','Verify fund disbursement for financing #{operationReference}.','NORMAL','ROLE_OPERATOR',3,'EVENT_EXECUTION','["disbursement","follow-up"]','en',8),
('TRADE_FINANCING','CREATE_FINANCING','REMINDER','RECOMMENDED','Pre-Maturity Rollover Evaluation','Evaluate rollover possibility for financing #{operationReference} before maturity.','NORMAL','ROLE_MANAGER',-30,'EXPIRY_DATE','["rollover","maturity"]','en',9),
('TRADE_FINANCING','CREATE_FINANCING','TASK','OPTIONAL','Complete Digital File','Digitize financing #{operationReference} documentation.','LOW','ROLE_OPERATOR',5,'EVENT_EXECUTION','["documentation","archive"]','en',10),
('TRADE_FINANCING','CREATE_FINANCING','FOLLOW_UP','OPTIONAL','Country Risk Monitoring','Review country risk for #{applicantName}.','LOW','ROLE_MANAGER',10,'EVENT_EXECUTION','["risk","country"]','en',11),
('TRADE_FINANCING','CREATE_FINANCING','REMINDER','OPTIONAL','Periodic Status Review','Periodic review of financing #{operationReference}.','LOW','ROLE_OPERATOR',-60,'EXPIRY_DATE','["review","validity"]','en',12);

-- =============================================
-- AVAL_DESCUENTO — RECEIVE_DRAFT (Initial) — ES + EN
-- =============================================
INSERT INTO event_alert_template (operation_type, event_code, alert_type, requirement_level, title_template, description_template, default_priority, assigned_role, due_days_offset, due_date_reference, tags, language, display_order) VALUES
('AVAL_DESCUENTO','RECEIVE_DRAFT','DEADLINE','MANDATORY','Vencimiento Pagaré #{operationReference}','Pagaré #{operationReference} por #{formattedAmount} #{currency} vence el #{expiryDate}. Verificar presentación al cobro.','URGENT','ROLE_OPERATOR',-7,'EXPIRY_DATE','["vencimiento","critico","pagare"]','es',1),
('AVAL_DESCUENTO','RECEIVE_DRAFT','TASK','MANDATORY','Seguimiento presentación al cobro','Programar presentación al cobro del pagaré #{operationReference} al vencimiento.','HIGH','ROLE_OPERATOR',3,'EVENT_EXECUTION','["presentacion","cobro"]','es',2),
('AVAL_DESCUENTO','RECEIVE_DRAFT','COMPLIANCE_CHECK','MANDATORY','Verificación KYC/AML — #{applicantName}','Verificación compliance para pagaré #{operationReference} de #{applicantName}.','HIGH','ROLE_MANAGER',1,'EVENT_EXECUTION','["compliance","kyc","regulatorio"]','es',3),
('AVAL_DESCUENTO','RECEIVE_DRAFT','CLIENT_CONTACT','MANDATORY','Notificar recepción de pagaré','Notificar a #{applicantName} recepción de pagaré #{operationReference}.','NORMAL','ROLE_OPERATOR',0,'EVENT_EXECUTION','["cliente","notificacion"]','es',4),
('AVAL_DESCUENTO','RECEIVE_DRAFT','TASK','RECOMMENDED','Evaluar descuento del pagaré','Evaluar posibilidad de descuento del pagaré #{operationReference} por #{formattedAmount} #{currency}.','NORMAL','ROLE_MANAGER',5,'EVENT_EXECUTION','["descuento","evaluacion"]','es',5),
('AVAL_DESCUENTO','RECEIVE_DRAFT','REMINDER','RECOMMENDED','Verificar cobro comisiones','Confirmar cobro comisiones de pagaré #{operationReference}.','NORMAL','ROLE_OPERATOR',2,'EVENT_EXECUTION','["comisiones","cobros"]','es',6),
('AVAL_DESCUENTO','RECEIVE_DRAFT','COMPLIANCE_CHECK','RECOMMENDED','Revisión exposición crediticia','Evaluar exposición de #{applicantName} con pagaré #{operationReference}.','NORMAL','ROLE_MANAGER',7,'EVENT_EXECUTION','["riesgo","credito"]','es',7),
('AVAL_DESCUENTO','RECEIVE_DRAFT','DEADLINE','RECOMMENDED','Plazo protesto si impago','Iniciar protesto si pagaré #{operationReference} no es pagado al vencimiento.','HIGH','ROLE_OPERATOR',-3,'EXPIRY_DATE','["protesto","impago"]','es',8),
('AVAL_DESCUENTO','RECEIVE_DRAFT','FOLLOW_UP','RECOMMENDED','Seguimiento endoso','Verificar endoso correcto del pagaré #{operationReference}.','NORMAL','ROLE_OPERATOR',3,'EVENT_EXECUTION','["endoso","verificacion"]','es',9),
('AVAL_DESCUENTO','RECEIVE_DRAFT','TASK','OPTIONAL','Completar expediente digital','Digitalizar documentación de pagaré #{operationReference}.','LOW','ROLE_OPERATOR',5,'EVENT_EXECUTION','["documentacion","archivo"]','es',10),
('AVAL_DESCUENTO','RECEIVE_DRAFT','FOLLOW_UP','OPTIONAL','Monitoreo riesgo crediticio','Monitorear riesgo crediticio del librador del pagaré #{operationReference}.','LOW','ROLE_MANAGER',10,'EVENT_EXECUTION','["riesgo","credito","monitoreo"]','es',11),
('AVAL_DESCUENTO','RECEIVE_DRAFT','REMINDER','OPTIONAL','Revisión periódica estado','Revisión periódica de pagaré #{operationReference}.','LOW','ROLE_OPERATOR',-30,'EXPIRY_DATE','["revision","vigencia"]','es',12),
-- EN
('AVAL_DESCUENTO','RECEIVE_DRAFT','DEADLINE','MANDATORY','Draft Maturity #{operationReference}','Draft #{operationReference} for #{formattedAmount} #{currency} matures #{expiryDate}. Verify presentation for payment.','URGENT','ROLE_OPERATOR',-7,'EXPIRY_DATE','["maturity","critical","draft"]','en',1),
('AVAL_DESCUENTO','RECEIVE_DRAFT','TASK','MANDATORY','Payment Presentation Follow-up','Schedule presentation for payment of draft #{operationReference} at maturity.','HIGH','ROLE_OPERATOR',3,'EVENT_EXECUTION','["presentation","payment"]','en',2),
('AVAL_DESCUENTO','RECEIVE_DRAFT','COMPLIANCE_CHECK','MANDATORY','KYC/AML Verification — #{applicantName}','Compliance check for draft #{operationReference} of #{applicantName}.','HIGH','ROLE_MANAGER',1,'EVENT_EXECUTION','["compliance","kyc","regulatory"]','en',3),
('AVAL_DESCUENTO','RECEIVE_DRAFT','CLIENT_CONTACT','MANDATORY','Notify Draft Receipt','Notify #{applicantName} of draft #{operationReference} receipt.','NORMAL','ROLE_OPERATOR',0,'EVENT_EXECUTION','["client","notification"]','en',4),
('AVAL_DESCUENTO','RECEIVE_DRAFT','TASK','RECOMMENDED','Evaluate Draft Discount','Evaluate discount possibility for draft #{operationReference} of #{formattedAmount} #{currency}.','NORMAL','ROLE_MANAGER',5,'EVENT_EXECUTION','["discount","evaluation"]','en',5),
('AVAL_DESCUENTO','RECEIVE_DRAFT','REMINDER','RECOMMENDED','Verify Commission Collection','Confirm draft #{operationReference} commissions collected.','NORMAL','ROLE_OPERATOR',2,'EVENT_EXECUTION','["commissions","collections"]','en',6),
('AVAL_DESCUENTO','RECEIVE_DRAFT','COMPLIANCE_CHECK','RECOMMENDED','Credit Exposure Review','Evaluate #{applicantName} exposure with draft #{operationReference}.','NORMAL','ROLE_MANAGER',7,'EVENT_EXECUTION','["risk","credit"]','en',7),
('AVAL_DESCUENTO','RECEIVE_DRAFT','DEADLINE','RECOMMENDED','Protest Deadline if Unpaid','Initiate protest if draft #{operationReference} unpaid at maturity.','HIGH','ROLE_OPERATOR',-3,'EXPIRY_DATE','["protest","non-payment"]','en',8),
('AVAL_DESCUENTO','RECEIVE_DRAFT','FOLLOW_UP','RECOMMENDED','Endorsement Follow-up','Verify correct endorsement of draft #{operationReference}.','NORMAL','ROLE_OPERATOR',3,'EVENT_EXECUTION','["endorsement","verification"]','en',9),
('AVAL_DESCUENTO','RECEIVE_DRAFT','TASK','OPTIONAL','Complete Digital File','Digitize draft #{operationReference} documentation.','LOW','ROLE_OPERATOR',5,'EVENT_EXECUTION','["documentation","archive"]','en',10),
('AVAL_DESCUENTO','RECEIVE_DRAFT','FOLLOW_UP','OPTIONAL','Credit Risk Monitoring','Monitor drawer credit risk for draft #{operationReference}.','LOW','ROLE_MANAGER',10,'EVENT_EXECUTION','["risk","credit","monitoring"]','en',11),
('AVAL_DESCUENTO','RECEIVE_DRAFT','REMINDER','OPTIONAL','Periodic Status Review','Periodic review of draft #{operationReference}.','LOW','ROLE_OPERATOR',-30,'EXPIRY_DATE','["review","validity"]','en',12);
