-- V39: Create operation, swift message and event log tables
-- These tables support the CQRS read model for operations and messages

-- 1. Operation read model table
CREATE TABLE IF NOT EXISTS operation_readmodel (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    operation_id VARCHAR(50) NOT NULL UNIQUE,
    original_draft_id VARCHAR(100),
    product_type VARCHAR(50) NOT NULL,
    message_type VARCHAR(10) NOT NULL,
    reference VARCHAR(100) NOT NULL,
    stage VARCHAR(50) NOT NULL,
    status VARCHAR(30) NOT NULL,
    creation_mode VARCHAR(20),
    swift_message TEXT NOT NULL,
    currency VARCHAR(3),
    amount DECIMAL(18,2),
    issue_date DATE,
    expiry_date DATE,
    applicant_id BIGINT,
    applicant_name VARCHAR(200),
    beneficiary_id BIGINT,
    beneficiary_name VARCHAR(200),
    issuing_bank_id BIGINT,
    issuing_bank_bic VARCHAR(11),
    advising_bank_id BIGINT,
    advising_bank_bic VARCHAR(11),
    amendment_count INT DEFAULT 0,
    message_count INT DEFAULT 0,
    awaiting_response BOOLEAN DEFAULT FALSE,
    awaiting_message_type VARCHAR(10),
    response_due_date DATE,
    created_by VARCHAR(100),
    created_at DATETIME,
    approved_by VARCHAR(100),
    approved_at DATETIME,
    modified_by VARCHAR(100),
    modified_at DATETIME,
    version INT DEFAULT 1,
    INDEX idx_operation_product (product_type),
    INDEX idx_operation_status (status),
    INDEX idx_operation_stage (stage),
    INDEX idx_operation_reference (reference),
    INDEX idx_operation_awaiting (awaiting_response)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. SWIFT message read model table
CREATE TABLE IF NOT EXISTS swift_message_readmodel (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    message_id VARCHAR(50) NOT NULL UNIQUE,
    message_type VARCHAR(10) NOT NULL,
    direction VARCHAR(10) NOT NULL,
    operation_id VARCHAR(50),
    operation_type VARCHAR(50),
    sender_bic VARCHAR(11) NOT NULL,
    receiver_bic VARCHAR(11) NOT NULL,
    swift_content TEXT NOT NULL,
    field_20_reference VARCHAR(35),
    field_21_related_ref VARCHAR(35),
    currency VARCHAR(3),
    amount DECIMAL(18,2),
    value_date DATE,
    status VARCHAR(30) NOT NULL,
    ack_received BOOLEAN DEFAULT FALSE,
    ack_content TEXT,
    ack_received_at DATETIME,
    expects_response BOOLEAN DEFAULT FALSE,
    expected_response_type VARCHAR(10),
    response_due_date DATE,
    response_received BOOLEAN DEFAULT FALSE,
    response_message_id VARCHAR(50),
    triggered_by_event VARCHAR(50),
    generates_event VARCHAR(50),
    created_by VARCHAR(100),
    created_at DATETIME,
    sent_at DATETIME,
    delivered_at DATETIME,
    received_at DATETIME,
    processed_at DATETIME,
    processed_by VARCHAR(100),
    version INT DEFAULT 1,
    INDEX idx_swift_operation (operation_id),
    INDEX idx_swift_direction (direction),
    INDEX idx_swift_type (message_type),
    INDEX idx_swift_status (status),
    INDEX idx_swift_pending_response (expects_response, response_received)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. Operation event log read model table
CREATE TABLE IF NOT EXISTS operation_event_log_readmodel (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    event_id VARCHAR(50) NOT NULL UNIQUE,
    operation_id VARCHAR(50) NOT NULL,
    operation_type VARCHAR(50) NOT NULL,
    event_code VARCHAR(50) NOT NULL,
    event_sequence INT NOT NULL,
    swift_message_id VARCHAR(50),
    swift_message_type VARCHAR(10),
    message_direction VARCHAR(10),
    previous_stage VARCHAR(50),
    new_stage VARCHAR(50),
    previous_status VARCHAR(50),
    new_status VARCHAR(50),
    event_data JSON,
    executed_by VARCHAR(100),
    executed_at DATETIME,
    INDEX idx_event_operation (operation_id),
    INDEX idx_event_code (event_code),
    INDEX idx_event_sequence (operation_id, event_sequence)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 4. Event type configuration table
CREATE TABLE IF NOT EXISTS event_type_config_readmodel (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    event_code VARCHAR(50) NOT NULL,
    operation_type VARCHAR(50) NOT NULL,
    language VARCHAR(5) NOT NULL DEFAULT 'en',
    event_name VARCHAR(100) NOT NULL,
    event_description TEXT,
    help_text TEXT,
    outbound_message_type VARCHAR(10),
    inbound_message_type VARCHAR(10),
    valid_from_stages JSON,
    valid_from_statuses JSON,
    resulting_stage VARCHAR(50),
    resulting_status VARCHAR(50),
    icon VARCHAR(50),
    color VARCHAR(20),
    display_order INT DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    requires_approval BOOLEAN DEFAULT FALSE,
    approval_levels INT DEFAULT 1,
    is_reversible BOOLEAN DEFAULT FALSE,
    generates_notification BOOLEAN DEFAULT TRUE,
    allowed_roles JSON,
    created_at DATETIME,
    modified_at DATETIME,
    version INT DEFAULT 1,
    UNIQUE KEY uk_event_type_lang (event_code, operation_type, language),
    INDEX idx_event_operation_type (operation_type),
    INDEX idx_event_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 5. Event flow configuration table
CREATE TABLE IF NOT EXISTS event_flow_config_readmodel (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    operation_type VARCHAR(50) NOT NULL,
    from_event_code VARCHAR(50),
    from_stage VARCHAR(50),
    to_event_code VARCHAR(50) NOT NULL,
    conditions JSON,
    is_required BOOLEAN DEFAULT FALSE,
    is_optional BOOLEAN DEFAULT TRUE,
    sequence_order INT DEFAULT 0,
    language VARCHAR(5) DEFAULT 'en',
    transition_label VARCHAR(100),
    transition_help TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    INDEX idx_flow_operation (operation_type),
    INDEX idx_flow_from_stage (from_stage),
    INDEX idx_flow_to_event (to_event_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 6. SWIFT response configuration table
CREATE TABLE IF NOT EXISTS swift_response_config_readmodel (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    sent_message_type VARCHAR(10) NOT NULL,
    operation_type VARCHAR(50) NOT NULL,
    expected_response_type VARCHAR(10) NOT NULL,
    response_event_code VARCHAR(50),
    expected_response_days INT DEFAULT 5,
    alert_after_days INT DEFAULT 3,
    escalate_after_days INT DEFAULT 7,
    language VARCHAR(5) DEFAULT 'en',
    response_description VARCHAR(200),
    timeout_message VARCHAR(200),
    is_active BOOLEAN DEFAULT TRUE,
    UNIQUE KEY uk_response_config (sent_message_type, operation_type, language),
    INDEX idx_response_operation (operation_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
