-- =====================================================
-- Configure MT707 (LC Amendment) fields
-- According to SWIFT MT707 specification
-- https://www.paiementor.com/swift-mt707-amendment-documentary-credit/
--
-- Fields with compute: prefix are calculated automatically by backend
-- and should be hidden from the user form (is_required=0, component_type='hidden')
--
-- MT707 Mandatory Fields (per SWIFT spec):
-- :20: - Sender's Reference (TRN for this amendment transaction)
-- :21: - Related Reference (reference to original LC)
-- :26E: - Number of Amendment (sequence number)
-- :30: - Date of Amendment
-- =====================================================

-- =====================================================
-- COMPUTED FIELDS (hidden, auto-generated by backend)
-- =====================================================

-- Campo :20: Sender's Reference (TRN) - computed as unique amendment reference
-- This is the Transaction Reference Number for THIS amendment message
UPDATE swift_field_config_readmodel
SET is_required = 0,
    component_type = 'hidden',
    draft_field_mapping = 'compute:amendmentTrn',
    help_text = 'Referencia única de la transacción de enmienda (auto-generada)'
WHERE message_type = 'MT707' AND field_code = ':20:';

-- Campo :21: Related Reference - computed from operation reference
-- This is the reference to the ORIGINAL LC being amended
UPDATE swift_field_config_readmodel
SET is_required = 0,
    component_type = 'hidden',
    draft_field_mapping = 'compute:reference',
    help_text = 'Campo calculado automáticamente (referencia de la LC original)'
WHERE message_type = 'MT707' AND field_code = ':21:';

-- Campo :26E: Number of Amendment (Mandatory per SWIFT spec, but auto-computed)
INSERT INTO swift_field_config_readmodel
(id, message_type, field_code, field_name, description, is_required, is_active, display_order, section, language, draft_field_mapping, field_type, component_type, help_text)
VALUES
('MT707-26E-es', 'MT707', ':26E:', 'Número de Enmienda', 'Número secuencial de la enmienda', 0, 1, 3, 'AMENDMENT_DETAILS', 'es', 'compute:amendmentNumber', 'TEXT', 'hidden', 'Campo calculado automáticamente'),
('MT707-26E-en', 'MT707', ':26E:', 'Number of Amendment', 'Sequential amendment number', 0, 1, 3, 'AMENDMENT_DETAILS', 'en', 'compute:amendmentNumber', 'TEXT', 'hidden', 'Auto-computed field')
ON DUPLICATE KEY UPDATE
    is_required = 0,
    is_active = 1,
    component_type = 'hidden',
    draft_field_mapping = 'compute:amendmentNumber',
    help_text = VALUES(help_text);

-- Campo :30: Date of Amendment (Mandatory per SWIFT spec, but auto-computed)
INSERT INTO swift_field_config_readmodel
(id, message_type, field_code, field_name, description, is_required, is_active, display_order, section, language, draft_field_mapping, field_type, component_type, help_text)
VALUES
('MT707-30-es', 'MT707', ':30:', 'Fecha de Enmienda', 'Fecha en que se realiza la enmienda', 0, 1, 4, 'AMENDMENT_DETAILS', 'es', 'compute:currentDate', 'DATE', 'hidden', 'Campo calculado automáticamente (fecha actual)'),
('MT707-30-en', 'MT707', ':30:', 'Date of Amendment', 'Date when amendment is made', 0, 1, 4, 'AMENDMENT_DETAILS', 'en', 'compute:currentDate', 'DATE', 'hidden', 'Auto-computed field (current date)')
ON DUPLICATE KEY UPDATE
    is_required = 0,
    is_active = 1,
    component_type = 'hidden',
    draft_field_mapping = 'compute:currentDate',
    help_text = VALUES(help_text);

-- =====================================================
-- FIX MISSING FIELD MAPPINGS (required for amendment detection)
-- These fields need draft_field_mapping to detect changes
-- =====================================================

-- Campo :31D: Date and Place of Expiry - needs mapping to detect changes
UPDATE swift_field_config_readmodel
SET draft_field_mapping = 'expiryDate'
WHERE field_code = ':31D:' AND (draft_field_mapping IS NULL OR draft_field_mapping = '');

-- =====================================================
-- OPTIONAL FIELDS (visible, editable by user)
-- =====================================================

-- Campo :52A: Issuing Bank (Optional per SWIFT spec)
INSERT INTO swift_field_config_readmodel
(id, message_type, field_code, field_name, description, is_required, is_active, display_order, section, language, draft_field_mapping, field_type, component_type)
VALUES
('MT707-52A-es', 'MT707', ':52A:', 'Banco Emisor', 'BIC del banco emisor de la LC', 0, 1, 5, 'BANKS', 'es', 'issuingBankBic', 'TEXT', 'bic-lookup'),
('MT707-52A-en', 'MT707', ':52A:', 'Issuing Bank', 'BIC of the LC issuing bank', 0, 1, 5, 'BANKS', 'en', 'issuingBankBic', 'TEXT', 'bic-lookup')
ON DUPLICATE KEY UPDATE
    is_active = 1,
    draft_field_mapping = 'issuingBankBic',
    component_type = 'bic-lookup';

-- =====================================================
-- Verify final configuration
-- =====================================================
SELECT field_code, field_name, is_required, component_type, draft_field_mapping
FROM swift_field_config_readmodel
WHERE message_type = 'MT707' AND language = 'en'
ORDER BY display_order;
